Feature/orchestrator balance check
nekromant322/platform pull request #10
Opened 2022-02-07 17:18 UTC by free2fqn

Запилил вьюшку для баланса с ссылочкой на его пополнение.

2022-02-07 17:59 UTC, nekromant322 requested changes
api для доступа к балансу

2022-02-07 20:03 UTC, free2fqn commented
@nekromant322 пофиксил, но не уверен, что хорошо складывать все эндпоинты в PageController. Возможно нужен отдельный еще один rest-controller?

2022-02-08 01:36 UTC, nekromant322 requested changes

2022-02-08 01:36 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +    @GetMapping("/admin/rest/balance")
Сюда складывать не надо, этот контроллер только чтоб возвращать пустые странички до появления отдельного "сервера" с фронтом, вынести в отдельный контроллер со звучным названием и убери зависимость на notificationFeign

2022-02-08 01:36 UTC, nekromant322 commented on platform_orchestrator/src/main/resources/application.yml
> +    id: ${SMS_API_ID}
зачем здесь?

2022-02-08 01:36 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +import org.springframework.web.bind.annotation.RequestBody;
ненужные импорты

2022-02-08 01:36 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +    @GetMapping("admin/balancePage")
вынести в отдельный контроллер, не использовать префикс /admin, потом в конфиге секурити паттернами ендпоинты засекурятся

2022-02-08 01:36 UTC, nekromant322 commented on platform_orchestrator/src/main/resources/templates/balance-check.html
> +</html>
можно бы добавить отдельный хедер для страничек админа, где была бы навигация для остальных ютилити штук типо просмотра отчетов и еще всякого разного

2022-02-08 01:36 UTC, nekromant322 commented on platform_orchestrator/src/main/resources/templates/balance-check.html
> +</html>
пример можно посмотреть в папке fragments

2022-02-08 01:43 UTC, nekromant322 commented
как на счет обработать ситуацию аля "сервис нотификаций не отвечает" или "сервис отвечает, но баланс получить все равно ничего не смог"

2022-02-08 09:25 UTC, free2fqn commented
> как на счет обработать ситуацию аля "сервис нотификаций не отвечает" или "сервис отвечает, но баланс получить все равно не смог" (отвечает 500)

теперь логируется эксепшен, когда сервис нотификаций не отвечает

2022-02-08 13:07 UTC, nekromant322 requested changes

2022-02-08 13:07 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/NotificationController.java
> +        return urlToReplenishBalance;
как на счет объекдинить в дто и взвращать вместе с балансом? зачем лишние вызовы на бэк делать?

2022-02-08 13:07 UTC, nekromant322 commented on platform_orchestrator/src/main/resources/templates/balance-check.html
> +    </nav>
сделать фрагментом, чтоб подключать на другие страницы админа удобно было, см пример в папке fragments

2022-02-08 13:07 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/NotificationController.java
> +        return balance;
не уверен, что что контроллер предназначен для этого  
еще я бы бросал все таки 500, тогда фронту будет легко понять что все наебнулось  (с адекватным сообщением об ошибке, разумеется)
А собственно сама обработка пусть будет на фронте (получили 500 - нарисовали красную надпись)

2022-02-09 16:59 UTC, nekromant322 requested changes

2022-02-09 16:59 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/feign/SmsRuFeign.java
> +    BalanceResponseFromSmsRuFeignClientDTO getBalance(@PathVariable String apiID);
-> `SmsRuBalanceResponseDTO`

2022-02-09 16:59 UTC, nekromant322 commented on platform_orchestrator/src/main/resources/templates/fragments/admin-navbar.html
> +        <li class="nav-item">
а где линк на проверку баланса в хедере админа?

2022-02-09 22:31 UTC, nekromant322 approved these changes

2022-02-09 22:32 UTC, merged