Feature/default review questions
nekromant322/platform pull request #106
Opened 2022-07-05 12:23 UTC by SofiaK01

добавила панель со стандартными вопросами к ревью и страницу для их редактирования

2022-07-05 14:15 UTC, Alekshas reviewed
И еще желательно куда нить скрины добавить какой табличка получилась, а то я чет нигде не нашел)

2022-07-05 14:15 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/model/DefaultQuestion.java
> +    private int section;
Возможно следует между полями добавить места для лучшей читаемости) Типо того

    @Column
    private String question;

    @Column
    private String chapter;

    @Column
    private int section;

2022-07-05 14:15 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/service/DefaultQuestionService.java
> +    private PlatformUserService platformUserService;
Так же добавь ентер

2022-07-05 16:25 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/DefaultQuestionRestController.java
> +        return new ResponseEntity<>(defaultQuestionService.findAll(), HttpStatus.OK);
а зачем тут ResponseEntity?

2022-07-05 16:25 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/DefaultQuestionRestController.java
> +    public ResponseEntity<List<DefaultQuestion>> findDefaultQuestionsByChapterAndSection(@RequestBody DefaultQuestionDTO defaultQuestionDTO) {
аналогично

2022-07-05 16:25 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/DefaultQuestionRestController.java
> +    public ResponseEntity<String> patchDefaultQuestion(@RequestBody DefaultQuestion defaultQuestion) {
-//-

2022-07-05 16:25 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/DefaultQuestionRestController.java
> +    public ResponseEntity<String> editDefaultQuestion(@RequestBody DefaultQuestion defaultQuestion) {
-//-

2022-07-05 16:25 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/DefaultQuestionRestController.java
> +    public ResponseEntity<String> delete(@RequestBody int id) {
-//-

2022-07-05 16:26 UTC, nekromant322 commented on platform_dto/src/main/java/dto/DefaultQuestionDTO.java
> +    private int section;
а почему тут нет самого вопроса?

2022-07-05 16:26 UTC, nekromant322 commented on platform_dto/src/main/java/dto/DefaultQuestionDTO.java
> +
пустая строка

2022-07-05 16:26 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/model/DefaultQuestion.java
> +        this.section=section;
ctrl+alt+L

2022-07-05 16:27 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/model/DefaultQuestion.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
а вот тут принято вще пустую строку перед @Id делать

2022-07-05 16:29 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
> +import org.springframework.web.bind.annotation.RestController;
в чем смысол?

2022-07-05 16:30 UTC, nekromant322 commented on platform_dto/src/main/java/dto/DefaultQuestionDTO.java
> +    private int section;
кажется понял, стоит добавить джава док с указанием для чего это ДТО вообще нужно

2022-07-05 16:30 UTC, nekromant322 requested changes
Много минорных чейнджей, так по задаче все ок

2022-07-12 16:56 UTC, nekromant322 commented on platform_orchestrator/pom.xml
> +        <jacoco.min.coverage>0.57</jacoco.min.coverage>
не, так не пойдет

2022-07-12 17:36 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/service/DefaultQuestionServiceTest.java
> +    void save() {
public

2022-07-12 17:42 UTC, nekromant322 approved these changes

2022-07-12 17:45 UTC, merged