При обновлении данных пользователя, email и номер телефона сохраняютс…
nekromant322/platform pull request #120
Opened 2022-07-16 20:25 UTC by MitsubishiLancerEvolutionX

…я в notification

2022-07-16 20:26 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/repository/RecipientRepository.java
> +    Recipient getRecipientByLogin(String login);
а чем метод выше не устроил?

2022-07-16 20:27 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/RecipientService.java
> +            repository.save(recipient);
а если передали только что-то одно? то что в базе уже было заменишь на null?

2022-07-16 20:27 UTC, nekromant322 requested changes
Протестировать еще разок и исправить затирание данных в notification

2022-07-17 12:43 UTC, nekromant322 commented
> Протестировать еще разок и исправить затирание данных в notification

а, ну еще тесты упавшие починить

2022-07-18 15:01 UTC, MitsubishiLancerEvolutionX commented
Поправил свои косяки и упавшие тесты

2022-07-18 15:14 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/RecipientService.java
> +            if(!recipientDTO.getEmail().equals("")) {
а точно тут проверка не на null должна быть?)

2022-07-18 15:14 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/RecipientService.java
> +                recipient.setPhoneNumber(recipientDTO.getPhoneNumber());
аналогично

2022-07-18 15:15 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/PersonalDataRestController.java
> +        notificatorFeign.saveRecipient(recipientDTO);
не стоит писать бизнес логику в конртоллерах

2022-07-18 15:16 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/PersonalDataRestController.java
> +        } else {
а чем null не устроил?  null - значит нет номера
а ты присылаешь пустую строку в notification зачем-то

2022-07-20 07:31 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/PersonalDataRestController.java
> +        notificatorFeign.saveRecipient(recipientDTO);
логика то все еще в контроллере

2022-07-20 07:31 UTC, nekromant322 requested changes
перенести отправку запроса в notification в какой-нибудь сервис

2022-07-21 21:05 UTC, nekromant322 approved these changes

2022-07-22 07:51 UTC, Alekshas approved these changes

2022-07-22 11:30 UTC, merged