find bad students and send messages to them and mentors
nekromant322/platform pull request #138
Opened 2022-07-27 17:18 UTC by SofiaK01

пока не работает

2022-07-28 17:41 UTC, SofiaK01 commented
@SofiaK01 всё починила 
жду ваших комментариев 🥳

2022-07-28 18:50 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/scheduler/AlertScheduler.java
> +     */
гоу на русском для единообразия и понятности

2022-07-28 18:50 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/AlertService.java
> +    PlatformUserService platformUserService;
private

2022-07-28 18:50 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/AlertService.java
> +    NotificatorFeign notificatorFeign;
private

2022-07-28 18:51 UTC, nekromant322 commented on platform_orchestrator/src/main/resources/application.yml
> +
сделать более осмысленное название  
в будущем планируется внедрения функционала, который отслеживает тех кто не приходил на ревью, будет похожая пропертя

2022-07-28 18:51 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +    NotificatorFeign notificatorFeign;
private

2022-07-28 18:53 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/AlertService.java
> +            String adminMessage = student.getLogin() + " давно ничего не делает и нуждается в мотивационных пинках";
уточнить сообщение аля, добавить "за n дней ни одного решения на платформе  
also в задачке вроде было указано, что применять этот алгоритм надо только к тем кто учится на CORE

2022-07-28 18:53 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/AlertService.java
> +                notificatorFeign.saveRecipient(studentRecipientDTO);
не нужно тут сохранять нового получателя, предполгается что он уже будет в бд потому что заполнил свои данные сразу после регистрации

2022-07-28 18:54 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/AlertService.java
> +                    notificatorFeign.saveRecipient(adminRecipientDTO);
аналогично

2022-07-28 18:54 UTC, nekromant322 requested changes
Искать только неактивных студентов, изучающих кор + много минорных правок

2022-07-29 14:46 UTC, SofiaK01 commented
@SofiaK01 исправила

2022-07-30 21:40 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/scheduler/AlertScheduler.java
> +    @Scheduled(cron = "0 00 10 * * ?")
а можем сделать настраиваемым из конфигов?

2022-07-31 10:30 UTC, seenister submitted a review, later dismissed

2022-08-01 19:46 UTC, SiaProjects approved these changes, later dismissed

2022-08-02 15:35 UTC, seenister approved these changes

2022-08-02 17:32 UTC, MitsubishiLancerEvolutionX approved these changes

2022-08-03 17:11 UTC, nekromant322 approved these changes

2022-08-03 17:13 UTC, merged