Feature/transfer tgbot data
nekromant322/platform pull request #14
Opened 2022-02-15 09:21 UTC by kemenchik

2022-02-15 10:25 UTC, free2fqn commented on platform_code_executor/src/main/java/com/override/service/test/HelloWorldTaskTest.java
>  public class HelloWorldTaskTest extends AbstractTaskTest {
Я не догоняю - что за файлы должны этим тестироваться?

2022-02-15 10:26 UTC, nekromant322 requested changes

2022-02-15 10:26 UTC, nekromant322 commented on platform_bot/src/main/java/com/override/PlatformBot.java
> +        }
может хоть немножко залогировавть?  
если потом вылезет боком, то заебемся искать

2022-02-15 10:26 UTC, nekromant322 commented on platform_code_executor/src/main/java/com/override/service/test/HelloWorldTaskTest.java
> +
это шо тут делает?

2022-02-15 10:26 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/RegisterStudentRequestDTO.java
> +    String chatId;
name -> telegramUserName  
default -> private

2022-02-15 10:26 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/ResponseJoinRequestDTO.java
> +public class ResponseJoinRequestDTO {
нейминг неудачный

2022-02-15 10:27 UTC, nekromant322 commented
минимальные правки накинул, еще позже досмотрю, запущу-потыкаю, щас нет времени

2022-02-15 10:27 UTC, kemenchik commented on platform_code_executor/src/main/java/com/override/service/test/HelloWorldTaskTest.java
> +
Это почему-то осталось с прошлой ветки, я вроде от мейна создавал, но уберу

2022-02-15 10:28 UTC, kemenchik commented on platform_code_executor/src/main/java/com/override/service/test/HelloWorldTaskTest.java
>  public class HelloWorldTaskTest extends AbstractTaskTest {
Это почему-то осталось с прошлой ветки, я вроде от мейна создавал, но уберу

2022-02-18 18:04 UTC, nekromant322 approved these changes

2022-02-18 18:05 UTC, merged