Added constraints on changing personal data
nekromant322/platform pull request #141
Opened 2022-07-29 16:50 UTC by SiaProjects

Добавил ограничения на изменение персональных данных. На стороне фронта сделал блокировку поля, если данные были введены. На стороне бэка сделал проверку на сервисном уровне на изменении не обновляемых персональных данных. В случае попытки изменить не обновляемые данные выбрасывается исключение

2022-07-30 16:50 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/PersonalDataService.java
> +    private boolean isUpdateLockedData(PersonalData oldData, PersonalData newData) {
имя метода не очень удачное

2022-07-30 16:53 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/PersonalDataService.java
> +                    if((field.get(oldData) != null) && (field.get(oldData) != field.get(newData))) { return true; }
насыпать \n не скупясь   
олсо я вот смотрю и как будто что-то не так

2022-07-30 16:55 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/PersonalDataService.java
> +    private boolean isUpdateLockedData(PersonalData oldData, PersonalData newData) {
возможно стоит вынести в Utils, чтобы потом можно было переиспользовать для других сущностей  
если сделать типизированным, то ваще сказка

2022-07-30 19:46 UTC, SiaProjects commented on platform_orchestrator/src/main/java/com/override/util/CheckerUnupdatableField.java
> +                            (field.get(currentValue) != field.get(newValue))) {
Тут что-то код поехал, идея очень сопротивляется на /n-ки

2022-07-30 19:48 UTC, SiaProjects commented
Вынес метод в отдельный класс, сделал параметры generic. С названиями туго давалось, так что жду идей, как обозвать методы/класс лучше, если будут мысли, как сделать понятнее

2022-07-31 09:12 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/util/CheckerUnupdatableField.java
> +    public boolean unupdatableFieldIsChanged(T currentValue, T newValue) {
можно сделать статик

2022-07-31 09:12 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/util/CheckerUnupdatableField.java
> +public class CheckerUnupdatableField<T> {
UtilityClass

2022-07-31 09:12 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/PersonalDataService.java
> +        PersonalData currentPersonalData = platformUserService.findPlatformUserByLogin(login).getPersonalData();
npe не может быть?

2022-07-31 09:12 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/PersonalDataService.java
> +    private CheckerUnupdatableField<PersonalData> checker;
Utilityclass

2022-07-31 09:12 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/PersonalDataService.java
> +            throw new UnupdatableDataException("Attempt to change data in the locked field");
Может эту ошибку и выбрасывать в методе проверки, а не здесь?

2022-07-31 10:24 UTC, seenister commented on platform_orchestrator/src/main/java/com/override/service/PersonalDataService.java
> +            throw new UnupdatableDataException("Attempt to change data in the locked field");
++

2022-07-31 17:01 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/CheckerUnupdatableField.java
> +    public boolean unupdatableFieldIsChanged(T currentValue, T newValue) {
чтоб потом страдать в тестах? отличная идея

2022-08-02 00:17 UTC, nekromant322 requested changes
Добавить тесты на CheckerUnupdatableField

2022-08-05 20:33 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/CheckerUnupdatableField.java
> +public class CheckerUnupdatableField<T> {
-> UnupdatableFieldChecker

2022-08-05 20:34 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/service/PersonalDataServiceTest.java
>      }
добавить тест в случае, если чекер бросает эксепшон

2022-08-05 20:35 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/utils/CheckerUnupdatableFieldTest.java
> +}
какой класс ты тестируешь?
Тебе же надо проверить логику работы CheckerUnupdatableField, а ты его мокаешь

2022-08-05 20:35 UTC, nekromant322 requested changes
Нужно разобраться с тестами

2022-08-11 12:28 UTC, nekromant322 approved these changes

2022-08-11 16:58 UTC, SofiaK01 approved these changes

2022-08-11 17:02 UTC, seenister approved these changes

2022-08-12 08:11 UTC, merged