Created pdf file upload/download features
nekromant322/platform pull request #148
Opened 2022-08-11 16:07 UTC by SiaProjects

Сделал функцию загрузки и скачивания файла
![image](https://user-images.githubusercontent.com/105119881/184178450-118e843c-8f71-4ff8-8635-08ac5227ca2a.png)

После создания отчета и нажатия кнопки принял оффер, появляется форма для загрузки файла на сервер
![image](https://user-images.githubusercontent.com/105119881/184178781-aa41730a-c79b-4a3f-b0a4-125e77bec43f.png)

Файл сохраняется в бд в виде blob файла
![image](https://user-images.githubusercontent.com/105119881/184178952-85914b2d-0c7a-4b3f-ae32-c6e99946a996.png)

После загрузки файла вместо формы появляется кнопка для скачивания файла
![image](https://user-images.githubusercontent.com/105119881/184179105-a5577dd2-d493-42ad-af4e-015b50585341.png)

2022-08-11 16:08 UTC, SiaProjects commented
После того как начал чистить код, обнаружил ошибку при скачивания файла

2022-08-11 16:09 UTC, SiaProjects commented on platform_dto/src/main/java/dto/InterviewReportDTO.java
> +    private String statusFile;
Этого не должно быть

2022-08-11 16:10 UTC, SiaProjects commented on platform_orchestrator/src/main/java/com/override/controller/OfferDocumentController.java
> +}
Все System.out уберутся, как решу проблему со скачиванием

2022-08-11 16:30 UTC, nekromant322 commented
@SiaProjects я бы ближе к ресту этот контроллер подтянул
GET_offer_document?reportId=...
PUT_offer_document?reportId=..

2022-08-15 18:16 UTC, nekromant322 submitted a review, later dismissed

2022-08-15 19:23 UTC, nekromant322 approved these changes

2022-08-16 11:52 UTC, nekromant322 approved these changes, later dismissed

2022-08-17 17:02 UTC, SofiaK01 requested changes

2022-08-17 17:02 UTC, SofiaK01 commented on platform_orchestrator/src/main/java/com/override/service/OfferDocumentService.java
> +        if(offerDocument == null) { return OfferDocumentDTO.builder().build(); }
пробела не хватает после иф)

2022-08-17 17:02 UTC, SofiaK01 commented on platform_orchestrator/src/main/resources/static/js/interviewReport.js
> +    downloadBtn.className = "download btn-success";
![Screenshot 2022-08-17 at 19 30 36](https://user-images.githubusercontent.com/53154670/185193541-7339a87f-02a9-4b4b-8598-71aacd8bcacb.jpg)
здесь бы добавить еще btn чтобы кнопочка была по стилю на остальные похожа

2022-08-17 17:12 UTC, seenister submitted a review, later dismissed

2022-08-17 18:02 UTC, SofiaK01 approved these changes

2022-08-17 18:06 UTC, MitsubishiLancerEvolutionX approved these changes

2022-08-17 18:12 UTC, merged