Feature/bqfi 59/connect check style
nekromant322/platform pull request #154
Opened 2022-08-16 18:06 UTC by MitsubishiLancerEvolutionX

Подключил checkStyle. Из проверок нужно было подключить только эти.
![image](https://user-images.githubusercontent.com/92749312/184945675-5b0b9d10-648d-4525-8b93-8234659b6c80.png)
Все проверки лежат в файле checkstyle.xml. К каждому модулю проверки сделал комментарий, чтобы в общем было понятно, за что отвечает каждый модуль.
![image](https://user-images.githubusercontent.com/92749312/184946391-2dc79b3c-4e89-49bd-8a1c-e5bdb76e5658.png)
Подправил весь код в проекте, который не проходит эти проверки. Мог что-то упустить из проверок. А еще в некоторых моментах сам не знаю, как правильно. Например, между полями я разрешил НЕ делать отступы, хз, правильно это или нет.
А так же сделал так, что несоблюдение правил checkStyle ломает сборку. Как только смержу эту ветку, допишу в Confluence инфу, типа как посмотреть ошибки, куда формируется отчет об ошибках и т.д.

2022-08-16 18:07 UTC, nekromant322 commented
@MitsubishiLancerEvolutionX починить конфликты

2022-08-17 12:14 UTC, nekromant322 submitted a review, later dismissed
Если билд с плохим кодстайлом фейлится - то ок, можно мержить

2022-08-17 16:09 UTC, seenister commented on platform_bot/src/main/java/com/override/PlatformBot.java
на 43 строке, после "else if (update.hasCallbackQuery()) {" надо пробел убрать

2022-08-17 16:09 UTC, seenister commented on platform_code_executor/src/main/java/com/override/exception/AssertionError.java
>          this.fExpected = expected;
на 12 строчке тоже стоит убрать пробел

2022-08-17 16:09 UTC, seenister commented on platform_code_executor/src/main/java/com/override/service/CompilerService.java
71 строчка - пробел)

2022-08-17 16:09 UTC, seenister commented on platform_code_executor/src/main/java/com/override/service/test/AbstractTaskTest.java
62 строчка-пробел)) глянь еще в остальных файлах пробелы

2022-08-17 18:59 UTC, SofiaK01 requested changes

2022-08-17 18:59 UTC, SofiaK01 commented on checkstyle.xml
> +        <!-- Бесполезные проверки импорта, такие как: 1. Не используется 2. Дублирование 3. Импорт java.lang 4. Импорт в той же упаковке, что и этот клас -->
мб проверки бесполезных импортов?

2022-08-17 20:09 UTC, SofiaK01 approved these changes

2022-08-17 20:13 UTC, SiaProjects approved these changes

2022-08-17 20:14 UTC, merged