Added feature of checking personal data by the admin when filling in by the student
nekromant322/platform pull request #157
Opened 2022-08-21 09:54 UTC by SiaProjects

Добавил в проект функцию проверки персональных данных при заполнении их студентом. Данные проверяются только в том случае, когда студент заполнил обязательные поля.

При заполнении обязательного поля и отправке формы данные сохраняются в таблицу временного хранения данных для проверки.
![image](https://user-images.githubusercontent.com/105119881/185785291-07cc4679-ca7c-4626-9c1d-05a1de7a1e1a.png)
![image](https://user-images.githubusercontent.com/105119881/185785363-8c0b2a63-bbed-40d6-a00f-70768b42fe35.png)

После отправки на проверку, на странице с персональными данными появляется надпись, которая уведомляет, что данные еще находятся на проверке.
![image](https://user-images.githubusercontent.com/105119881/185785322-8735ea0b-a84a-4c4e-a002-bbe32e544c09.png)

При этом данные таблицы с персональными данными не меняются до окончания проверки.
![image](https://user-images.githubusercontent.com/105119881/185785396-1c46698e-952b-433f-9bb2-4e6e075e8912.png)

Когда админ заходит на страницу всех студентов появляется кнопка с запросом на проверку данных напротив студента, который пытается заполнить обязательные поля.
![image](https://user-images.githubusercontent.com/105119881/185785430-33027556-91f7-4e93-9c9b-ebc5d94f69a5.png)

Админ может редактировать поля по своему усмотрению и сохранить изменения нажав на кнопку отправки формы.
![image](https://user-images.githubusercontent.com/105119881/185785485-9406e40f-8168-4b48-b470-6e210996b3bf.png)

После того, как админ согласовал изменения, данные сохраняются в основной таблице с персональными данными, а данные в таблице временного хранения данных удаляются.
![image](https://user-images.githubusercontent.com/105119881/185785508-20a22a87-6cf4-486f-ad77-e3648d23d69b.png)
![image](https://user-images.githubusercontent.com/105119881/185785565-8611b84e-7a93-45ad-a85d-d94a19196bd6.png)

2022-08-21 12:43 UTC, nekromant322 commented
@SiaProjects Можно ли внести правки (студенту) до согласования? Сложно ли будет такое докинуть?

2022-08-24 17:35 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/PersonalDataRestController.java
> +    public void saveUsersPersonalData(@RequestBody PersonalData personalData,
свагер описания больше в заблуждения вводят, ей богу

2022-08-24 17:36 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/model/PersonalData.java
> +            example = "222L")
возможно стоит такое в дто бахать 
хз почему тут не разделен транспортный слой с бд, стоит озаботится, а то мы потеряемся в аннотациях (ну не только поэтому)

2022-08-24 17:36 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/model/RequestPersonalData.java
> +    @Column(name = "contractNumber")
аналогично про дто

2022-08-24 17:36 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/model/RequestPersonalData.java
> +    }
стоит вынести в маппер

2022-08-24 17:38 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/PersonalDataService.java
> +    public void saveOrSendToCheck(PersonalData newPersonalData, String login) {
см S из SOLID  
лучше разделить на два метода  
```
if(check()) {  
send()  
} else  {   
...  
}
```

2022-08-24 17:39 UTC, nekromant322 requested changes
изобрести дто, подправить по мелочи

2022-08-26 07:13 UTC, SiaProjects commented on platform_orchestrator/src/main/java/com/override/model/PersonalData.java
> +            example = "222L")
Смысл бахать описание в ДТО? 
Когда заходишь на адрес свагера, ищешь контроллер и в этом контроллере в параметрах стоит моделька эта, как раз и работает это описание параметров. Я попробую конечно, но если только перенести описание в дто, то есть ощущение, что теряется смысл существования этого описания.

2022-08-26 07:17 UTC, SiaProjects commented on platform_orchestrator/src/main/java/com/override/model/PersonalData.java
> +            example = "222L")
А на сколько имеет смысл на существование идея запихивать в параметр с @RequestBody ДТО с описанием свагера, а на сервисном уровне мапером получать модель?

2022-08-26 07:37 UTC, SiaProjects commented on platform_orchestrator/src/main/java/com/override/model/PersonalData.java
> +            example = "222L")
Если идея реализуема, то тогда описание и правда можно будет бахнуть в ДТО

2022-08-29 19:06 UTC, nekromant322 approved these changes

2022-08-30 06:33 UTC, merged