Feature/reports (заглушка пока что)
nekromant322/platform pull request #16
Opened 2022-02-20 12:32 UTC by kemenchik

2022-03-02 15:38 UTC, nekromant322 requested changes
Как на счет связать сущность отчета с сущностью юзера?

2022-03-04 08:12 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/repositories/StudentReportRepository.java
> +    StudentReport findFirstByDateAndStudentLogin(LocalDate date, String login);
Спринг настолько умный, что даже такое разруливает, прикольно

2022-03-05 10:25 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/models/StudentReport.java
>      private LocalDate date;
Даже @Column на полях ставить не надо? О_о

2022-03-05 10:26 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/repositories/StudentReportRepository.java
> +    StudentReport findFirstByDateAndStudentLogin(LocalDate date, String login);
Крутота

2022-03-05 10:43 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/service/CustomStudentDetailService.java
> +    public static class CustomStudentDetails implements UserDetails {
Объясни пжлст, зачем делать статичный класс публичным? 
Я думал, что внутренние статические классы нужны в случаях, когда они применимы только в конкретном классе. Тут мы видим, что CustomUserDetails используется не только здесь и надо делать его публичным. 
Не лучше ли вынести в отдельный класс?

2022-03-05 10:43 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/service/ReportService.java
> +            return new ResponseEntity<>("Уже есть отчет на эту дату", HttpStatus.CONFLICT);
А почему возвращаемое ResponseEntity не параметризуется?
Или тут достаточно, что метод возвращает ResponseEntity<String>?

2022-03-05 10:46 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/ReportService.java
> +            return new ResponseEntity<>("Уже есть отчет на эту дату", HttpStatus.CONFLICT);
Потому что видно, чем оно параметризовано сходя из того, что я положил в конструктор
Называется diamond оператор, можно почитать

2022-03-05 10:47 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/CustomStudentDetailService.java
> +    public static class CustomStudentDetails implements UserDetails {
Тут хз, как по мне, эти классы точно связаны, поэтому я думаю, что можно его здесь и оставить

2022-03-05 10:48 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/models/StudentReport.java
>      private LocalDate date;
А зачем?

2022-03-05 16:44 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/models/StudentReport.java
>      private LocalDate date;
просто удивляюсь)

2022-03-05 19:56 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/CustomStudentDetailService.java
> +    public static class CustomStudentDetails implements UserDetails {
я бы тоже здесь оставил, потому что сам по себе этот класс никакой дополнительной логики не несет, а нужен чтоб скормить его спрингу  
если будет в отдельном месте мало что изменится

2022-03-05 19:58 UTC, nekromant322 approved these changes

2022-03-05 19:59 UTC, nekromant322 approved these changes

2022-03-07 00:07 UTC, merged