Алертинг "Давно не был на ревью"
nekromant322/platform pull request #161
Opened 2022-08-26 01:57 UTC by Silchukelisa

Оповещения для менторов о студентах, которые давно не приходили на ревью

2022-08-26 13:36 UTC, MitsubishiLancerEvolutionX commented on platform_orchestrator/src/main/java/com/override/service/ReviewAlertService.java
> +        }
Это не сильно важно, но все же переменную adminMessage лучше создавать хотя бы внутри блока if, типа зачем эта переменная, если мы все равно сообщение отправлять не будем. Лучше сразу в метод sendMessage вторым аргументом передавать строку "студент " + student.getLogin() + " давно не был на ревью ", и вообще не создавать никакую переменную с сообщением.

2022-08-26 13:36 UTC, MitsubishiLancerEvolutionX commented on platform_orchestrator/src/main/java/com/override/repository/ReviewRepository.java
> +
Не уверен по поводу данного метода в реализации логики. Попробую объяснить, если что поправьте меня. Этот метод возвращает же только первую запись из таблицы ревью по нужному id. Я открыл ветку у себя и добавил такие данные в таблицу ревью
![image](https://user-images.githubusercontent.com/92749312/186898953-221302a7-26ee-41a5-93ef-467d6afbd544.png)
У студента с id=12 было два ревью, 11 и 25 числа. И вроде как все норм, никаких уведомлений админу приходить не должно, но уведомление мне пришло (я предварительно сделал себя админом)
![image](https://user-images.githubusercontent.com/92749312/186899197-d5493e1f-cb59-4675-856c-e395d284e17f.png)
Насколько я понимаю, это произошло как раз потому, что метод вернул из талицы как раз первую запись о ревью (на 11 число), ну и логично прошло больше 7 дней и в телеграмм пришло сообщение.
И тут надо либо последнюю запись брать (хотя они не всегда в таблице идут по порядку, скорее всего это связано с возможностью отмены, переноса и т.д.), либо возвращать ревью с самой последней датой.
Это только мои предположения, возможно я что-то не так понял.

2022-08-26 13:36 UTC, MitsubishiLancerEvolutionX commented on platform_orchestrator/src/main/java/com/override/repository/ReviewRepository.java
> +
И еще один момент по поводу метода. Тестовые данные в таблице сделаны таким образом, что у каждого студента есть хотя бы одна запись в таблице ревью. А если представить ситуацию, что пользователь только что зашел на платформу и у него еще ревью не было. Я попробовал смоделировать ситуацию и убрал у одного студента все записи ревью (id = 11 у студента):
![image](https://user-images.githubusercontent.com/92749312/186903702-36f9d54d-10c0-46d2-af90-4b7384e3ed2e.png)
И вот что выдал оркестратор, когда была проверка последнего ревью у студентов:
![image](https://user-images.githubusercontent.com/92749312/186904057-547da113-400d-415f-a249-c8be0ec08286.png)
Может лучше вместо  Review findFirstByStudentId(Long userId) использовать Optional<Review>findFirstByStudentId(Long userId)???

2022-08-26 13:36 UTC, MitsubishiLancerEvolutionX commented on platform_orchestrator/src/main/java/com/override/repository/ReviewRepository.java
> +
Optional<Review>findFirstByStudentId(Long userId)

2022-08-26 13:36 UTC, MitsubishiLancerEvolutionX commented on platform_orchestrator/src/main/java/com/override/repository/ReviewRepository.java
> +
Почему-то дженерик у Optional убирает)))

2022-08-29 06:54 UTC, SiaProjects approved these changes, later dismissed

2022-08-29 07:00 UTC, SiaProjects commented
Возможно стоит добавить тесты еще

2022-08-29 19:00 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/scheduler/ReviewAlertScheduler.java
> +}
Обхединить с AlertScheduler

2022-08-29 19:01 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/ReviewAlertService.java
> +    }
тоже перенести в существующий сервис + написать тесты

2022-08-29 19:01 UTC, nekromant322 requested changes
тесты + перенос

2022-09-02 18:54 UTC, MitsubishiLancerEvolutionX approved these changes, later dismissed

2022-09-13 18:12 UTC, SiaProjects commented on platform_orchestrator/src/test/java/com/override/service/AlertServiceTest.java
> +                        Collections.singletonList(new Authority(null, "admin")), new PersonalData(), new UserSettings()));
Возможно стоит вынести в utils, как статичные методы генерации списков админов и юзеров (если их еще нет)

2022-09-13 18:16 UTC, SiaProjects commented on platform_orchestrator/src/test/java/com/override/service/AlertServiceTest.java
> +        verify(notificatorFeign, times(1)).sendMessage(students.get(0).getLogin(), DAYS.between(codeTryRepository.findFirstByUserIdOrderByDate(students.get(0).getId()).getDate(), LocalDateTime.now())
DAYS.beetwen стоит вынести в переменную, чтобы не прописывать одно и то же несколько раз. Так и код будет выглядеть приятнее

2022-09-13 19:00 UTC, SiaProjects commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +    public List<PlatformUser> getStudentsByLastReview(long daysForReview) {
Добавить тест

2022-09-13 19:01 UTC, SiaProjects commented on platform_orchestrator/src/test/java/com/override/service/AlertServiceTest.java
> +        CodeTry codeTry1 = new CodeTry();
Сделать один codeTry

2022-09-15 20:05 UTC, nekromant322 approved these changes

2022-09-15 20:12 UTC, merged