Фильтр для отчета студента
nekromant322/platform pull request #166
Opened 2022-09-02 18:51 UTC by MitsubishiLancerEvolutionX

Сделал фильтр для отчета студента. Смысл в том, что если у студента нет отчета за последние три дня, то блокируется доступ к платформе. При входе на платформу его перебрасывает на страничку для написания отчета "/report". При попытке перейти на любую другую страничку (без разницы как, по URL или нажатием на нужную кнопку), его будет редиректить на "/report". Если студент напишет отчет на любой день из последних трех, он вернет себе доступ к функционалу платформы.

Подправил создание тестовых данных для таблицы отчетов студентов, чтобы не блокировать им доступ к платформе. Теперь при инициализации у каждого студента будет один отчет за вчерашний день.

2022-09-13 18:41 UTC, SiaProjects commented on platform_orchestrator/src/main/java/com/override/config/ReportFilter.java
> +        HttpServletRequest httpRequest = (HttpServletRequest) servletRequest;
-> HttpServletRequest httpRequest = (HttpServletRequest) servletRequest;
-> String token = jwtFilter.getTokenFromRequest(httpRequest);

2022-09-15 20:02 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/config/PermitAllURLs.java
> +
а это разве нельзя объединить?

2022-09-15 20:03 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/config/ReportFilter.java
> +            }
вот тут можно просто проверять ссылки которые еще Соня писала, просто накинь в тот список своих еще

2022-09-15 20:03 UTC, nekromant322 requested changes
Минорные чейнджы + неплохо бы написать тестов на этот фильтр

2022-09-19 19:01 UTC, nekromant322 approved these changes

2022-09-20 08:25 UTC, SiaProjects approved these changes

2022-09-20 17:06 UTC, merged