feature/lessons-widget-scaling WIP
nekromant322/platform pull request #17
Opened 2022-02-22 09:09 UTC by free2fqn

Ребята, я в тупике. Пытаюсь сделать сервис, который собирает JSON, отражающий структуру глав/степов/уроков на платформе. Вложенность ограниченная (делаю вручную ибо тупой и с обходом не вывез).
Не бейте по рукам за использование вывода в консоль и мейна, благодаря им я понимаю, что моя функция точно знает о существовании уроков:
![image](https://user-images.githubusercontent.com/22982519/155098716-623d9231-363c-4659-a24f-9fdd949dcb98.png)
Но на постман приходит такая лабуда, уже без уроков:
![image](https://user-images.githubusercontent.com/22982519/155099289-d68c7fcc-bf56-4c97-ab76-d3150f273f89.png)
Прошу помощи, что я проглядел и почему у меня "обрезаются" списки уроков?

2022-02-22 10:00 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/LessonStructureServiceImpl.java
> +        String stringPathToCourse = "C:\\Users\\Schneider\\IdeaProjects\\platform\\platform_orchestrator\\src\\main\\resources\\templates\\lessons" + "\\" + courseName;
-> относительный путь?

2022-02-22 10:02 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/LessonStructureServiceImpl.java
> +        return lessonStructureDTO; //почему возвращается без уроков? в консоли уроки выводятся
понятия не имею почему, ты же разработчик, а не я, продебажь

2022-02-22 10:04 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/exception/LessonStructureException.java
> +public class LessonStructureException extends BaseOrchestratorException{
ну, если будет вылетать этот эксепшон, то он будет отрабатываться эдвайсом, статус без явного указания INTERNAL_SERVER_ERROR буит

2022-02-22 10:05 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/LessonController.java
> +            // почему здесь нужен try-catch? все IOException ловятся уже в lessonStructureService.getDirectoryStructure()
вроде не нужен, там throws нет нигде

2022-02-26 19:13 UTC, free2fqn commented
проблему обозначил TODO в последнем коммите

2022-02-26 19:55 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/LessonStructureServiceImpl.java
> +        String stringPathToCourse = "C:\\Users\\Schneider\\IdeaProjects\\platform\\platform_orchestrator\\src\\main\\resources\\templates\\lessons" + "\\" + courseName;
Полный путь все еще

2022-02-26 19:57 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/PlatformOrchestratorApplication.java
> +//        }
Че это вообще

2022-02-26 19:58 UTC, kemenchik commented on platform_orchestrator/src/main/resources/static/js/lessonSidebar.js
> +window.onload = init("core");
Из window.href по урлу получать название курса

2022-02-27 22:49 UTC, nekromant322 requested changes
минорные правки и мержу

2022-02-27 22:49 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/LessonController.java
> +    }
гоу инжект через поля  
добавь, кстати в ридмик пометку об этом плз  
это, конечно, холивар, но я так люблю, так тестить удобно  и много чего еще

2022-02-27 22:49 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/LessonStructureService.java
> +        String stringPathToCourses = "platform_orchestrator/src/main/resources/templates/lessons"; /*C:\Users\Schneider\IdeaProjects\platform\platform_orchestrator\src\main\resources\templates\lesson
це шо

2022-02-27 22:49 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/LessonStructureService.java
> +        String stringPathToCourses = "platform_orchestrator/src/main/resources/templates/lessons"; /*C:\Users\Schneider\IdeaProjects\platform\platform_orchestrator\src\main\resources\templates\lesson
убери

2022-02-28 07:36 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/controller/LessonController.java
> +    }
Ок, поправлю. Начал делать так из-за того что вроде как рекомендовано избегать инжекта через поля

2022-02-28 09:13 UTC, kemenchik commented on platform_orchestrator/src/main/resources/templates/lessons/core/introduction/step1/2.html
> +<html lang="en">
Нет импорта thymleaf, мб работать не будет

2022-02-28 09:13 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/LessonStructureService.java
> +@Slf4j
Есть аннотация, но нет логов нигде

2022-02-28 09:13 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/controller/LessonController.java
> +    LessonStructureService lessonStructureService;
На сколько мне известно, такие места лучше делать приватными

2022-02-28 09:13 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/LessonStructureService.java
> +    }
Есть геттер, но поле не приватное

2022-02-28 09:13 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/LessonStructureService.java
> +    private void postConstruct() {
Имя метода не очень, лучше написать для чего он нужен

2022-02-28 09:13 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/LessonStructureService.java
> +                .collect(Collectors.toList());
Что-то подсказывает, что где-то должна быть проверка на то, что это папка, мало ли что

2022-02-28 09:13 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/PlatformOrchestratorApplication.java
> +        ApplicationContext context = SpringApplication.run(PlatformOrchestratorApplication.class, args);
Это зачем? реально не понимаю

2022-02-28 09:20 UTC, free2fqn commented on platform_orchestrator/src/main/resources/templates/lessons/core/introduction/step1/2.html
> +<html lang="en">
работает

2022-02-28 09:28 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/controller/LessonController.java
> +    LessonStructureService lessonStructureService;
у меня было private final и инжектил через конструктор - @nekromant322 сказал инжектить через поле.

2022-02-28 09:34 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/service/LessonStructureService.java
> +                .collect(Collectors.toList());
Курсы добавляются не от балды, а по правилам оформления, с ограничением глубины. Я так понимаю что файлы там появиться не могут

2022-02-28 09:34 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/PlatformOrchestratorApplication.java
> +        ApplicationContext context = SpringApplication.run(PlatformOrchestratorApplication.class, args);
oops, не подчистил

2022-02-28 10:20 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/controller/LessonController.java
> +    LessonStructureService lessonStructureService;
Так private не запрещает через филд инжектить

2022-02-28 12:29 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/controller/LessonController.java
> +    LessonStructureService lessonStructureService;
пофиксил

2022-02-28 13:36 UTC, nekromant322 approved these changes

2022-02-28 13:37 UTC, merged