Логирование http запросов
nekromant322/platform pull request #178
Opened 2022-09-26 20:07 UTC by Silchukelisa

2022-09-26 22:48 UTC, nekromant322 commented
@Silchukelisa Как выглядит лог?

2022-09-27 18:04 UTC, nekromant322 commented on platform_bot/src/main/java/com/override/config/CustomRequestLoggingInterceptor.java
> +        log.info("preHandle => Request URL: {}", requestURL);
зачем это в логе?

2022-09-27 18:05 UTC, nekromant322 commented on platform_bot/src/main/java/com/override/config/CustomRequestLoggingInterceptor.java
> +        log.info("preHandle => Request URL: {}", requestURL);
всм Prehandle  after  и вот это все

2022-09-27 18:05 UTC, nekromant322 requested changes
Мб вынести в стартер и его подключить во все микросервисы?

2022-10-10 23:46 UTC, Horus1613 commented
Есть готовое решение в виде logbook
Возможно, если его причесать определенным образом - получится элегантное решение для логирования

2022-10-16 22:14 UTC, nekromant322 commented on platform_bot/src/main/java/com/override/config/LoggingFilter.java
> +                    request.getMethod(), request.getRequestURI(), response.getStatus(), map);
если будешь оставлять такой вариант логирования то сильно ускориться до режима турбо поможет перемещение этой проверки выше (зря мапка с хедерами набивается)

2022-10-16 22:16 UTC, nekromant322 commented on platform_bot/src/main/java/com/override/config/LoggingFilter.java
> +public class LoggingFilter extends OncePerRequestFilter {
если не logbook, то давай стартер все таки замутим:
отдельный модуль в проекте с нанванием ака override-logging-starter  
в нем единственная автоконфигурация, которая помещает в контекст бин LoggingFilter вот в таком виде  
будет очень элегантно подключаться в помник + менять надо будет при случае в одном месте

2022-10-19 17:22 UTC, nekromant322 approved these changes

2022-10-19 17:26 UTC, merged