WIP JWT + auth
nekromant322/platform pull request #18
Opened 2022-02-23 14:11 UTC by kemenchik

для регистрации админа нужно зайти на ендпоинт /admin-register, дается токен, его положить в куки (если через постман),
для регистрации чела нужно запустить бота, к нему с /register отправить запрос, после чего через админа апрувнуть запрос на join/request/accept, у которого в боди ID запроса, в личку придут креды, через них можно на /login войти и дадут токен, его положить в куки(если через постман)

2022-02-24 20:17 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/AdminController.java
> +    }
эта что

2022-02-24 20:19 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/models/StudentAccount.java
> +@Table(name = "account_credential_t")
почему такое название таблицы? мб пусть совпадает в именем сущности?

2022-02-25 07:36 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/models/StudentAccount.java
> +@Table(name = "account_credential_t")
> почему такое название таблицы? мб пусть совпадает в именем сущности?

Там же не только студенты

2022-02-25 07:37 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/controller/rest/AdminController.java
> +    }
> эта что

Ендпоинт для админа (типа проверка), пока что не привязан к админ панели,

2022-02-27 01:11 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +        PlatformUser account = new PlatformUser(null, login, password, null, roles);
схуяли null в chatId? вроде юзер в админа превращается из студента-юзера, у него стопудово есть chatId

2022-02-27 01:16 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/AuthorityInit.java
> +    }
дико неудобно, давать все таки что-то вроде  
![image](https://user-images.githubusercontent.com/43813324/155864221-2d1d0816-1f1b-4f51-bd96-d230e1765f6f.png)

2022-02-27 01:17 UTC, nekromant322 requested changes
инициализацию дефолтных юзеров я бы сделал по умолчанию, я со временем при выкатке перенесу это в dev профиль, а для разработки пока пусть будет дырявое, это ок

2022-02-27 08:40 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +        PlatformUser account = new PlatformUser(null, login, password, null, roles);
> Owner

Потому что это метод на создание админа, тут нет еще студента-юзера, это в дев профиль нужно

2022-02-27 08:59 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +        PlatformUser account = new PlatformUser(null, login, password, null, roles);
Так то там есть отдельно метод для апдейта, и там все норм

2022-02-28 20:43 UTC, nekromant322 requested changes

2022-02-28 20:43 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/AdminController.java
> +    @PostMapping("/update-student/{id}")
тут более удачный нейминг может быть  
аля promote...

2022-02-28 20:43 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/AuthController.java
> +    }
а зачем этот ендпоинт то по итогу нужен?

2022-02-28 21:21 UTC, nekromant322 approved these changes

2022-02-28 21:29 UTC, merged