Authorizarion in VK Notifications has been added
nekromant322/platform pull request #191
Opened 2022-12-01 22:24 UTC by Tolmachevsky

В личном кабинете в разделе уведомления добавлена возможность авторизоваться в ВК для получения уведомлений через бота Platform.

2022-12-02 17:30 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/controller/RecipientController.java
> +    }
у меня немного не укладывается то что здесь написано в башке
`setVkChatID` с аргументом login  внутри вызов `vkService.getMessages`

2022-12-04 13:36 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +                            System.out.println(message.toString());
?

2022-12-05 22:52 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/config/CacheConfig.java
> +}
как это к привязке вк чатов относится?

2022-12-05 22:52 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/controller/RecipientController.java
> +    }
`/recipient/get/{login}` зачем тут /get/??? разве это не http метод?

2022-12-05 22:53 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/controller/RecipientController.java
> +    }
зачем отдельный ендпоинт, если есть общий для получения recipient по login?

2022-12-05 22:55 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/controller/RecipientController.java
> +    }
как это связано с сущностью Recipient? см REST и как его готовить

2022-12-05 22:56 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +    }
выглядит пиздец страшно  
точно нельзя побить на методы поменьше?  
чето я не вижу тестов на этот метод, хотел бы я посмотреть как ты юнит тестов на такое добро наклепаешь :)

2022-12-05 22:57 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        }
мб эксепшон бросать чтоб сразу статус **не** 200 ок от сервиса отлетал?  
зачем сознательно npe плодить

2022-12-05 22:58 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/SecurityCodeRestController.java
> +    String getSecurityCode(@PathVariable("login") String login){
-> public   
и поработать над неймингом урлов  
опять же см REST

2022-12-05 22:59 UTC, nekromant322 requested changes
подвигать чуть ближе к ресту и порефакторить

2022-12-06 01:02 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        while (true) {
а это не блокирует поток навсегда в случае если никто не ответил?

2022-12-06 01:03 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        Integer[] result = {null};
зачем нужны эти массивы?

2022-12-06 05:47 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        }
Там в getVkChatIdFromBot() есть проверка на null, в этом случае бот ответит "Вы ввели неверный код.". Если бросать эксепшон мы и бота положим, а так можно ввести верный код без перезагрузки бота.

2022-12-06 05:54 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        while (true) {
Если никто не ответит, через некоторое время метод упадет из-за RetryableException : Read timed out executing GET http://notification/recipient/getVkChatId/...

2022-12-06 05:56 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        Integer[] result = {null};
Обход final в лямбде, но можно сделать и нормально, согласен

2022-12-06 06:27 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/controller/RecipientController.java
> +    }
Так а зачем мне recipient, я тут получаю код подтверждения. Или эту логику нужно запихать в findRecipientByLogin?

2022-12-06 07:04 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/controller/RecipientController.java
> +    }
Наверное, понял тебя

2022-12-06 07:04 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/config/CacheConfig.java
> +}
Удалил

2022-12-06 07:05 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/controller/RecipientController.java
> +    }
Убрал гет

2022-12-06 07:24 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        Integer[] result = {null};
Убрал

2022-12-06 07:25 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        while (true) {
Стоит установить количество циклов? Или как это правильно ограничить?

2022-12-06 07:35 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/service/VkService.java
> +    }
Не оч понимаю как тут можно побить на методы. Разве что 1 строку вместо 2. Можно подсказку?

2022-12-06 17:56 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        }
окей, допустим, хотя все еще выглядит не лучшим образом

2022-12-06 19:01 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        while (true) {
не знаю как правильно, просто из того, что вижу - это упадет при хоть какой-либо нагрузке  
потоки просто закончатся  
мб это можно решить так - в отдельном потоке (одном)  всегда бот слушает вк и следит что там пишут, если че-то приходит - накидывает в кеш/бд, а мы в бизнесовом коде уже этим пользуемся  
что думаешь?

2022-12-06 19:02 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/controller/RecipientController.java
> +    }
я о том, что это вообще не про recipient, это что-то другое совсем)

2022-12-06 19:03 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        }
как минимум это залупа коня, потому что 
` if (data.get(code) == null) {
            return null;
        }`  
        можно смело заменить на `data.get(code)`

2022-12-06 19:03 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        }
и ничего не изменится

2022-12-07 11:40 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        }
мне еще с результатом data.get(code) в этом методе взаимодействовать надо, метод возвращает String, а не Cache.ValueWrapper

2022-12-09 18:34 UTC, Horus1613 requested changes

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/controller/VkController.java
> +    @GetMapping("/securityCode/{login}")
Как по мне, логичнее делать path = {login}/securityCode/

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/controller/VkController.java
> +    public ResponseEntity<Integer> getVkChatId(@PathVariable("login") String login) {
Хорошо бы, придерживаться консистентности кода
Если один метод котроллера возвращает ResponseEntity
То и второй лучше сделать через ResponseEntity

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/controller/RecipientController.java
> +    RecipientDTO getRecipient(@PathVariable("login") String login) {
public

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/controller/RecipientController.java
> +    @GetMapping("/recipient/{login}")
В остальных путях
сущность /recipients/
значит тут тоже стоит буковку s оставить

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/mapper/RecipientMapper.java
> +                .vkChatId(recipient.getVkChatId().orElse("None"))
Ну, окей, мб вам так по бизнесу надо
Но выглядит странно

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        Random random = new Random();
Лучше сделать бином и инжектить

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +public class VkService extends Thread {
Честно, не понял плясок с потоком
если это для лонгпула
почему не через шедулер?

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +                if (!messages.isEmpty()) {
Что бы не было такой сильной вложенности, лучше делать конструкции аля
```

if (messages.isEmpty()) {
    return;
}

 for (Message message : messages) {
    ....
  }

```

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +                        try {
try внутри try - не хорошо
Как вариант - вынести в отдельный метод

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +                                data.put(code, String.valueOf(message.getFromId()));
Тут NPE будет, если нет кэша

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        data.put(login, stringBuilder.toString());
Тут NPE будет, если нет кэша

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        Cache data = cacheManager.getCache("vkSecurityCode");
Хорошо бы название кэшей куда-нибудь определить в переменные

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        if (data.get(login) == null) {
Тут NPE будет, если нет кэша

2022-12-09 18:34 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        String securityCode = (String) cacheCode.get();
.get() параметризируется
принудительный каст не нужен

2022-12-09 18:34 UTC, Horus1613 commented on platform_orchestrator/src/main/java/com/override/controller/rest/SecurityCodeRestController.java
> +    @GetMapping("/securityCode/{login}")
Как по мне, логичнее делать path = {login}/securityCode/

2022-12-09 18:34 UTC, Horus1613 commented on platform_orchestrator/src/main/java/com/override/service/UserSettingsService.java
> +            for (int i = 0; i < NUMBER_OF_ATTEMPTS; i++) {
Костыльненько получилось
Оберни лучше вызовы Feign в Spring Retry
Там же спокойно ямлом настраиваются кол-во попыток, бэкофф периоды и тд

2022-12-09 18:34 UTC, Horus1613 commented on platform_orchestrator/src/main/java/com/override/service/UserSettingsService.java
> +        if (recipientDTO.getVkChatId().equals("None") && userSettings.getVkNotification().equals(true)) {
Вот вообще не очевидно мне как стороннему читателю
Почему None
И откуда оно вообще взялось
Лучше уж null или на крайний случай ""

2022-12-09 18:34 UTC, Horus1613 commented on platform_orchestrator/src/main/java/com/override/service/UserSettingsService.java
> +            Integer res = notificatorFeign.getVkChatID(login);
А зачем тогда попытки выше?

2022-12-10 07:33 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/service/VkService.java
> +public class VkService extends Thread {
Шедулер не выделяет отдельный поток, а тут можно @PostConstruct повесить на Overrided run
Или я чо не понимаю?

2022-12-10 07:33 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        Random random = new Random();
VkApiClient & GroupActor?

2022-12-10 07:33 UTC, Tolmachevsky commented on platform_notification/src/main/java/com/override/service/VkService.java
> +                                data.put(code, String.valueOf(message.getFromId()));
Не будет, он создаст кэш "vkChatId"

2022-12-10 07:38 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +public class VkService extends Thread {
Почему не выделяет? 
Очень даже.
Причем ты можешь настроить его насчет пула тредов и тд
Собрав бин ThreadPoolTaskScheduler

2022-12-10 07:39 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +        Random random = new Random();
Ага, еще и Random сверху

2022-12-10 07:41 UTC, Horus1613 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +                                data.put(code, String.valueOf(message.getFromId()));
Если кто-то случайно выключит свойство dynamic в CaffeineCacheManager, то новый кэш не сделается
И будет NPE
![изображение](https://user-images.githubusercontent.com/47709487/206838885-b6322a7b-000b-405a-a078-6f1e0bf03b05.png)

2022-12-13 20:07 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/VkService.java
> +@Service("VkService")
Зачем тут айдишник?

2022-12-13 22:22 UTC, nekromant322 approved these changes

2022-12-13 22:58 UTC, merged