WIP
nekromant322/platform pull request #27
Opened 2022-03-06 12:52 UTC by ushackov

2022-03-07 00:05 UTC, nekromant322 requested changes

2022-03-07 00:05 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/CodeTryRestController.java
> +    StudentCodeService studentCodeService;
private

2022-03-07 00:05 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/CodeViewRestController.java
> +@RequestMapping("/codeView")
-> codeTry  
по имени основной сущности про которую контроллер

2022-03-07 00:05 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/CodeViewRestController.java
> +}
как-то не густо  
В задаче:  
"Создать рест апи, с помощью которого можно было бы потом отображать историю решений и иметь возможность их просматривать (картинка во вложении), сам фронт делать не надо"  
Ты на фронте для каждой задачи вообще ВСЕ решения будешь показывать или фильтровать из сотни объектов уже на фронте только те решения которые конкретно по открытой на экране задаче?  
Заставлю фронт писать за такие дела)

2022-03-07 00:05 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/mappers/CodeTryMapper.java
> +            , PlatformUser user) {
починить кодстайл

2022-03-07 00:05 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/models/CodeTry.java
> +    Long id;
private

2022-03-07 00:05 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/StudentCodeService.java
> +    CodeTryMapper mapper;
private

2022-03-07 00:05 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/StudentCodeService.java
> +public class StudentCodeService {
-> CodeTryService

2022-03-07 00:05 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/StudentCodeService.java
> +    CodeTryMapper mapper;
-> codeTryMapper  
чем больше кода - тем больше разных зависимостей у класса, в тч больше мапперов, зачем выдумывать лихо и потом ренеймить если можно по подсказке от идее нейминг делать?

2022-03-07 00:05 UTC, nekromant322 commented
Допилить рест апи, добавив методы, которые будут нужны на фронте (пофантазировать как бы рисовал фронт, какие данные и какие бы запросы делал)

2022-03-07 00:09 UTC, nekromant322 commented on pom.xml
> +            </dependency>
отдельным пул реквестом, из этой ветки выпилить
и прикрепить к задаче ссылку

2022-03-07 00:11 UTC, nekromant322 commented on pom.xml
> +            </dependency>
это не я такой капризный, это называется чистоплотностью  разработческой  
ну и к тому же это вполне полезно: Если ты делаешь большую фичу, пул реквест может пару недель висеть открытым, а тебе все новые и новые требования поступают  
А маленький фикс ты мог бы уже давно смержить и всем доброе дело сделать, а он вместе с фичей колбасится и задачка не закрывается

2022-03-07 19:32 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/controller/rest/CodeViewRestController.java
> +    public List<CodeTry> studentCodes(@AuthenticationPrincipal CustomStudentDetailService.CustomStudentDetails user) {
Сделай импорт статик, ну не красиво же

2022-03-07 19:32 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +    @Autowired
Что-то непонятное и финал и алларгсконструктор и автовайред над всем, нужно что-то одно выбрать

2022-03-07 19:32 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/controller/rest/CodeViewRestController.java
> +public class CodeViewRestController {
CodeTryRest... тогда уж

2022-03-07 19:32 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/models/CodeTry.java
> +    private Integer lesson;
А че бы не хранить в taskidentifier? Если он поменяется, тут тоже менять нужно будет

2022-03-07 19:35 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/models/CodeTry.java
> +    private Integer lesson;
@kemenchik потому что json в базу заливать такое, ибо поиск по ним тогда невозможен 
 а отдельную табличку под идентифкаторы заводить - дурость

2022-03-07 19:58 UTC, nekromant322 commented
Реши конфликты и напиши тесты на сервис и маппер

2022-03-10 12:05 UTC, free2fqn commented on platform_code_executor/src/main/java/com/override/service/test/AbstractTaskTest.java
>                                              "непонятная дичь:\n\n" + e.getMessage()))
Ламерский вопрос: зачем разделять эту и предыдущую строки?

2022-03-10 12:05 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/service/CustomStudentDetailService.java
> +    public static class CustomStudentDetails implements UserDetails {
Вот снова к вопросу о public static классах. Может в отдельный файл?

2022-03-10 12:05 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/controller/rest/CodeViewRestController.java
> +@RequestMapping("/codeTryRest")
Может лучше "/codeViewRest"?
Сходу так и не понять, почему контроллер CodeViewRestController, и маппинг codeTryRest

2022-03-10 12:05 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/mappers/CodeTryMapper.java
> +        return new CodeTry(null,
ламерский вопрос: а не лучше сделать конструктор без аргумента-айдишника, чтобы не передавать null?

2022-03-10 12:05 UTC, free2fqn commented on platform_orchestrator/src/test/java/com/override/service/CodeTryServiceTest.java
> +    @Mock(answer = Answers.CALLS_REAL_METHODS)
Интересная штука. Ламерский вопрос: а просто @Autowired или как-то по-другому заинжектить сюда бин нельзя, только через такой реалистичный мок?

2022-03-10 12:05 UTC, free2fqn commented on platform_orchestrator/src/test/java/com/override/service/CodeTryServiceTest.java
> +        verify(codeTryRepository, times(1)).save(Mockito.any(CodeTry.class));
ламерский вопрос: я правильно понимаю, что эта строчка проверяет, что у codeTryRepository был вызван метод save() всего один раз с любым аргументом класса CodeTry?

2022-03-10 12:14 UTC, ushackov commented on platform_orchestrator/src/test/java/com/override/service/CodeTryServiceTest.java
> +        verify(codeTryRepository, times(1)).save(Mockito.any(CodeTry.class));
Да проверяем что логика метода подразумевает вызов репозитория.

2022-03-10 13:18 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/CodeViewRestController.java
> +@RequestMapping("/codeTryRest")
Rest здесь явно лишний, как минимум

2022-03-10 13:20 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/mappers/CodeTryMapper.java
> +        return new CodeTry(null,
Еще вручную его писать((( мы к такому ради тестов не готовы. Надо было ставить ли... Котлин

2022-03-10 13:22 UTC, nekromant322 requested changes
Мне не нравится ток нейминг апи, а так все ок

2022-03-10 16:36 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
>  @RequiredArgsConstructor
Зачем?

2022-03-10 16:37 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/CodeTryRestController.java
> +    }
вот тут метод сервиса можно сделать чтоб принимал TaskIdentifierDTO

2022-03-11 09:01 UTC, free2fqn approved these changes

2022-03-11 09:01 UTC, free2fqn approved these changes

2022-03-11 09:29 UTC, nekromant322 approved these changes

2022-03-11 09:31 UTC, merged