Сервис вопросов к ревью
nekromant322/platform pull request #36
Opened 2022-03-18 22:08 UTC by ushackov

2022-03-19 16:48 UTC, nekromant322 requested changes
с главами не оч продумано, предложил как сделать лучше  
можно докинуть ендпоинт для фронта со списком всех глав

2022-03-19 16:48 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/QuestionDTO.java
> +    String question;
-> private

2022-03-19 16:48 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/QuestionDTO.java
> +    String question;
int для chapter мне кажется не очень подходит, лучше String
возможный список глав я думаю можно положить куда-то в конфиг, сейчас актуальный:  
core 1 + 2
core 3  
core 4  
core 5        
core 6  
web  
preproject 1  
preproject 2  
preproject 3  
interview

Чтоб можно было с фронта дернуть и отрисовать
тип вот так
![image](https://user-images.githubusercontent.com/43813324/159130291-adb41ca9-f440-455d-8af6-3e9cf2fa05e2.png)

2022-03-19 16:48 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/models/Question.java
> +    private PlatformUser user;
-> private
chapter аналогично

2022-03-19 16:48 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/QuestionService.java
> +
-> private

2022-03-19 16:48 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/mappers/QuestionMapperTest.java
> +    PlatformUserService platformUserService;
-> private

2022-03-19 16:48 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/service/QuestionServiceTest.java
> +    PlatformUserService platformUserService;
-> private

2022-03-19 16:57 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +
зачем?

2022-03-19 16:58 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
> +        questionService.delete(questionDTO);
а где ограничение, что это может сделать только админ?

2022-03-19 19:38 UTC, ushackov commented on platform_dto/src/main/java/dtos/QuestionDTO.java
> +    String question;
Может тогда не стринг, а ENUM?

2022-03-19 19:40 UTC, ushackov commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +
Страница с вопросами? Чем ендпоинт с пустой вьюхой не подходит?

2022-03-20 20:21 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
> +    LessonStructureService lessonStructureService;
-> private

2022-03-20 20:22 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
>      }
реально работает только для админов?  
такую аноташку не встречал

2022-03-20 20:24 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/models/Question.java
> +    private boolean answered;
@Column не надо?

2022-03-20 20:26 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/QuestionService.java
> +}
какой-то стремный patch у тебя  
глубоко в теории вопросик может потеряться, учитывая что две операции происходят не транзакционно  
патч логичнее сделать просто выставив новые значения полей у сущности с известным айдишником

2022-03-20 20:28 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/mappers/QuestionMapperTest.java
> +                .build());
странно выглядит  
гораздо логичнее было бы questionMapper.dtoToEntity(generateTestQuestionDTO())  
ну или что-то вроде того  
а то из пустого в порожнее переливаешь

2022-03-20 20:28 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/service/QuestionServiceTest.java
> +                generateTestQuestionDTO().getChapter());
два раза инициализируется тестовый объект  
с таким подходом тесты будут по 30 минут собираться, как в сбере

2022-03-20 20:29 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/service/QuestionServiceTest.java
> +        Question question = generateTestQuestion();
это скорее в блок "ожидаемый результат"

2022-03-20 20:29 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/service/QuestionServiceTest.java
> +        Question question = generateTestQuestion();
но это вкусовщина

2022-03-20 20:32 UTC, nekromant322 requested changes
Из важного - поправить стремный patch  
кстати я вот тут подумал, что можно воспользоваться решением которое за нас уже придумали ака Http Patch запрос  
да и вцелом rest api ну такое себе, как будто статью, которую я скидывал не читал(((

![image](https://user-images.githubusercontent.com/43813324/159184862-65a3c738-2ce1-4738-9566-30640d712b9b.png)

2022-03-21 09:56 UTC, ushackov commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
>      }
Реально работает

2022-03-21 09:57 UTC, ushackov commented on platform_orchestrator/src/main/java/com/override/models/Question.java
> +    private boolean answered;
Вообще не надо. Но поставил

2022-03-21 09:57 UTC, ushackov commented on platform_orchestrator/src/main/java/com/override/service/QuestionService.java
> +}
Переделал патч

2022-03-21 09:57 UTC, ushackov commented on platform_orchestrator/src/test/java/com/override/mappers/QuestionMapperTest.java
> +                .build());
пофиксил

2022-03-21 09:58 UTC, ushackov commented on platform_orchestrator/src/test/java/com/override/service/QuestionServiceTest.java
> +                generateTestQuestionDTO().getChapter());
пофиксил

2022-03-21 09:59 UTC, ushackov commented
Пофиксил вызовы разных методов из HTTP теперь все в одном ендпоинте с разными методами. Не знаю насколько это удобно. Но в принципе все работает. секьюрити тоже работает. Не знаю что с пустой вьюхой плохого. Подскажи я быстро сделаю.

2022-03-21 20:15 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/QuestionDTO.java
> +    String question;
-> private?

2022-03-21 20:16 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
> +    @DeleteMapping
у тебя хоть что-то святое есть?
сделай единообразный порядок аннотаций, глазу больно

2022-03-21 20:17 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/mappers/QuestionMapper.java
> +                .build();
не надо так  
давай мы будем из сервисов вызывать маперы, а не наоборот  
юзер можно стать параметром метода

2022-03-21 20:18 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
> +    @PatchMapping()
()?

2022-03-21 20:19 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
> +    public void delete(@RequestBody QuestionDTO questionDTO){
по айди? зачем полностью все лишний раз гонять

2022-03-21 20:21 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/QuestionService.java
> +        questionRepository.patchAnsweredById(questionDTO.isAnswered(), questionDTO.getId());
а как же изменение текста запроса?( в трелло это можно, очень даже удобно
более того, иногда надо вопрос перенести из одной главы в другую (когда по ошибке написал)

ваще хз зачем выдумывать лихо если вполне решается при помощи .save()

2022-03-21 20:21 UTC, nekromant322 requested changes
Ты смотришь на код, который написал?

2022-03-22 09:25 UTC, nekromant322 approved these changes

2022-03-24 14:11 UTC, merged