Статистика по количеству попыток студентов
nekromant322/platform pull request #39
Opened 2022-03-24 09:50 UTC by ushackov

4 графика, которые отражают
- самые сложные задачи(топ 5, 10, 20)
- Самые сложные этапы 
- количество попытое по студентам
- разбивка по статусам попыток

2022-03-24 09:58 UTC, nekromant322 requested changes, later dismissed

2022-03-24 09:58 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +    @GetMapping("/codeTry/stats")
пусть будет просто statistics в соответствии с именем вьюхи  
думаю там рядом еще разные графички будут жить

2022-03-24 09:58 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/CodeTryRestController.java
> +    }
Гоу это в StatisticsRestController запилим, потому что это с основным функционалом все таки не связано

2022-03-24 09:58 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/models/CodeTry.java
> +    @Column(name = "status")
а зачем в бд писать status? почему не оставить соответствие с ентити?

2022-03-24 09:58 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/repositories/CodeTryRepository.java
> +            "order by count desc limit 20", nativeQuery = true)
магическая константа  
которая к тому же по условию должна быть переменной

2022-03-24 09:58 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/CodeTryService.java
> +        for (int i = 0; i < size; i++) {
i < size вместо того чтоб из базы запросить строго нужное количество  
думаю стоит переделать

2022-03-24 12:28 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/service/CodeTryService.java
> +        List<Integer[]> statsOfHardTasks = codeTryRepository.countStatsOfHardTasks();
Стоит ли использовать Integer[] здесь и в CodeTryRepository? Может коллекцию коллекций?

2022-03-24 12:28 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/models/CodeTry.java
> +@Table(name = "code_try")
автоматически же будет code_try, нет?

2022-03-24 12:28 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/repositories/CodeTryRepository.java
> +            "order by count desc limit 20", nativeQuery = true)
Я не понял, о чем ты. Можно поподробнее, ты про nativeQuery?

2022-03-24 12:45 UTC, ushackov commented on platform_orchestrator/src/main/java/com/override/service/CodeTryService.java
> +        List<Integer[]> statsOfHardTasks = codeTryRepository.countStatsOfHardTasks();
Не знаю делал в соответствии с +++++ на stackoverflow. Толя рассуди?

2022-03-24 12:50 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/CodeTryService.java
> +        List<Integer[]> statsOfHardTasks = codeTryRepository.countStatsOfHardTasks();
Если заведется с листом листов, то можно и сделать  
но скорее всего не заведется  
впрочем попробовать никто не мешает

2022-03-24 13:19 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/service/StatisticsService.java
> +            mapOfStatus.put((String) obj[0], (BigInteger) obj[1]);
Я не понимаю, почему, но что-то внутри меня восстает против такого решения. Может создать какой-то класс, где красиво будут храниться данные, что-то вроде ДТО, только не шлем наружу, а храним внутри? Лист массивов объектов оч сильно смущает при прочтении

2022-03-24 13:19 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/service/StatisticsService.java
> +            mapOfStatus.put((String) obj[0], (BigInteger) obj[1]);
Ну и в других местах, соответственно, тоже

2022-03-25 08:10 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/mappers/CodeTryStatMapper.java
> +    public Map<String, BigInteger> listToMapCodeTryStatus(List<Object[]> codeTryStatus) {
listToMapStudentCodeTry и listToMapCodeTryStatus делают одно и тоже, зачем два разных метода?

2022-03-25 08:10 UTC, free2fqn commented on platform_orchestrator/src/main/java/com/override/service/StatisticsService.java
> +                codeTryRepository.countCodeTryByChapterAndStep());
Я правильно понимаю, что здесь мы достаем из репозитория кучу списков, которые по факту - мапы?
Может есть способ сделать мапы на уровне репозитория, вместо листов массивов?

2022-03-25 08:14 UTC, ushackov commented on platform_orchestrator/src/main/java/com/override/service/StatisticsService.java
> +                codeTryRepository.countCodeTryByChapterAndStep());
Можно сделать но только из отдельных данных, типа ключ глава или урок но не все вместе. Возможно есть какой то хак, но я нашел единственный способ.

2022-03-25 08:19 UTC, ushackov commented on platform_orchestrator/src/main/java/com/override/mappers/CodeTryStatMapper.java
> +    public Map<String, BigInteger> listToMapCodeTryStatus(List<Object[]> codeTryStatus) {
Я сознательно сделал два чтоб не путаться в мапах с разными данными

2022-03-25 08:21 UTC, nekromant322 requested changes
Осталось добавить тесты :р

2022-03-25 14:31 UTC, nekromant322 commented on platform_orchestrator/src/main/resources/templates/statistics.html
> +<header th:replace="fragments/common.html :: header"></header>
мб админский хедер?
и кстати в него эе линк на эту страницу добавить бы

2022-03-29 16:11 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/service/StatisticsServiceTest.java
> +    CodeTryStatMapper codeTryStatMapper;
-> private

2022-03-29 16:12 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/StatisticsService.java
> +        return codeTryStatMapper.entityToDto(codeTryRepository.countStatsOfHardTasks(size),
я бы назвал в духе getCodeTryStatistic  
потому что очевидно рядом будем еще другая статистика

2022-03-29 16:14 UTC, nekromant322 requested changes
Тесты по статистике ничего не проверяют  
Посмотри в сторону @SpringDataJpaTest  
Чтобы протестить как работают запросы  
Для тестов можно инициализировать ембеддед h2 бдшку в памяти

2022-04-06 10:47 UTC, nekromant322 approved these changes

2022-04-06 10:48 UTC, merged