Feature/test data initializer
nekromant322/platform pull request #40
Opened 2022-03-25 14:38 UTC by TrueMaxWell

Над генерируемыми значениями можно еще поработать, если есть надобность. Для теста вроде и так норм)

2022-03-25 14:45 UTC, nekromant322 requested changes

2022-03-25 14:45 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +        if (enableTestData) {
лучше заменить на @ConditionalOnProperty  
https://www.baeldung.com/spring-conditionalonproperty

2022-03-25 14:45 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +                    Role.USER);
Если это пароль, то лучше чтоб с логином совпадал, так тестировать проще

2022-03-25 14:45 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +                        new CodeTryDTO(
new CodeTryDTO(....) можно заменить на 
CodeTryDTO.builder().pole1(...).pole2(...).build();  
Тогда и от AllArgsConstructor можно избавиться, они со временем становятся очень монструозными и нечитаемыми

2022-03-25 14:45 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +                        new CodeTryDTO(
в целом актуально и для остальных моделек

2022-03-25 15:55 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +        UserInit();
с каких пор методы с большой буквы?

2022-03-25 15:55 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +    Faker faker = new Faker();
-> private  
-> @Autowired

2022-03-25 15:57 UTC, TrueMaxWell commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +        UserInit();
Они там были такие изначально, я по инерции))

2022-03-25 15:59 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +                        student.getLogin()));
а почему по одной попытке ток каждому?  
для наглядности можно сгенерить накинуть разных попыток, с разными результатами, для разных задач  
@ushackov может подкинуть тестовые данные свои, вероятно

2022-03-25 16:01 UTC, TrueMaxWell commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +                        student.getLogin()));
тестовые данные в плане для конкретных задач?

2022-03-25 16:01 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +                                .studentsCode(faker.funnyName().name())
вот тут впаять текст HelloWorld программы, чтоб понятно было что за шит тут в бдшке

2022-03-25 16:02 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +                        student.getLogin()));
в соседнем пул реквесте он статистику делает, и графички там на основе тестовых данных

2022-03-25 16:46 UTC, TrueMaxWell commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +                        student.getLogin()));
Можно генерить траи для каждого юзера и к каждой задаче пока не выпадет на рандоме статус OK. Я так понимаю задач еще нет в общем-то как и их количества. Что если к примеру задач будет 10 и по каждой таким образом метод пройдется?

2022-03-26 06:52 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +    private final Faker faker = new Faker();
Сделать бином?

2022-03-26 16:48 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +                        student.getLogin()));
@TrueMaxWell какая-то очень сложная схема
я бы взял просто 5 идентифкаторов  задач и захардкодил бы их  
каждому юзеру закинуть по 10 попыток решения каждой задачи с радномным результатом

2022-03-26 16:50 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/FakerService.java
> +}
эта што  
в конфигурационном классе просто сделай что-то типо  
@Bean
public Faker faker() {
return new Faker();
}

2022-03-26 16:53 UTC, TrueMaxWell commented on platform_orchestrator/src/main/java/com/override/service/FakerService.java
> +}
В каком?))

2022-03-26 16:55 UTC, TrueMaxWell commented on platform_orchestrator/src/main/java/com/override/service/FakerService.java
> +}
Просто не знал куда пихнуть, в какой конфиг

2022-03-28 07:52 UTC, nekromant322 approved these changes

2022-03-28 07:53 UTC, merged