Add instruction for Environment variables
nekromant322/platform pull request #41
Opened 2022-03-28 16:05 UTC by Alexander-Sharipov

Добавление переменных окружения (Environment variables):
-Edit Configurations -> Выбираем нужный стартер -> Вставляем нужные значения в строку как на картинке* -> Apply
(*если строка не отображается, то Modify options -> Environment variables (или Alt+E) -> Вставляем -> Apply)

2022-03-28 17:17 UTC, nekromant322 requested changes

2022-03-28 17:17 UTC, nekromant322 commented on README.md
> +- Edit Configurations -> Выбираем нужный стартер -> Вставляем нужные значения в строку как на картинке* -> Apply
Стартер -> сервис  
Откуда брать значения стоит написать

2022-03-28 18:44 UTC, nekromant322 commented on README.md
> +![image](https://user-images.githubusercontent.com/94536519/160442353-96da2387-de34-4fdd-8370-895ff792393a.png)
почему скриншот с примером эврики, для нее же ничего указывать не нужно -____-

2022-03-28 19:39 UTC, Alexander-Sharipov commented on README.md
> +![image](https://user-images.githubusercontent.com/94536519/160442353-96da2387-de34-4fdd-8370-895ff792393a.png)
потому что в остальных уже указаны значения, и я подумал, что смысл же в строке, а не сервисе

2022-03-28 21:03 UTC, nekromant322 commented on README.md
> +![image](https://user-images.githubusercontent.com/94536519/160442353-96da2387-de34-4fdd-8370-895ff792393a.png)
ну, это может вводить в заблуждение

2022-03-29 16:00 UTC, nekromant322 approved these changes

2022-03-29 16:06 UTC, merged