Фронт для вопросов
nekromant322/platform pull request #42
Opened 2022-03-29 22:24 UTC by TrueMaxWell

В целом все готово и работает

2022-03-30 08:12 UTC, nekromant322 requested changes

2022-03-30 08:12 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
> +                .getName());
думаю не очень резонно гонять туда сюда логин текущего пользователя  
на бэке его всегда можно очень быстро достать (посмотри как это делается в других контроллерах

2022-03-30 08:12 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
> +    PlatformUserService platformUserService;
-> private

2022-03-30 08:14 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
> +    }
добавил бы еще /questions/my/{chapter} или что-то вроде того, чтобы не мучаться, в попытках понять "кто я есть"

2022-03-30 10:08 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +
как на счет двух отдельных вьюшек для админа и юзера?
для админа повесить @Secured

2022-03-30 10:09 UTC, TrueMaxWell commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +
а чем такой вариант лучше будет?

2022-03-30 10:11 UTC, kemenchik commented on platform_orchestrator/src/main/resources/static/js/questions.js
> +                    currentUser.authorities[1].authority === 'ROLE_ADMIN') {
А если мы добавим третью роль, все сломается?

2022-03-30 10:12 UTC, TrueMaxWell commented on platform_orchestrator/src/main/resources/static/js/questions.js
> +                    currentUser.authorities[1].authority === 'ROLE_ADMIN') {
получается что так))
Переделаю

2022-03-31 23:20 UTC, TrueMaxWell commented
Добавил редактирование вопросов
![image](https://user-images.githubusercontent.com/90501949/161165007-8a557286-f474-4c8c-978c-0ffa0c7f7f16.png)

2022-04-01 15:56 UTC, nekromant322 approved these changes

2022-04-01 15:56 UTC, merged