Feature/booking review
nekromant322/platform pull request #43
Opened 2022-03-31 09:24 UTC by Alexander-Sharipov

2022-03-31 09:31 UTC, nekromant322 requested changes

2022-03-31 09:31 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +    public ResponseEntity<String> appointReview(Long id) {
appoint -> approve

2022-03-31 09:31 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/models/Review.java
> +    }
гетеры и сетеры для того чтоб получить и установить значение  
ни больше, ни меньше  
не надо располагать в них логику, перенеси в другой класс (не модельный)

2022-03-31 09:31 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/ReviewRestController.java
> +    // Ревью при этом сохраняется в бд, но со статусом confirmed(false), это значит что время забронированно, но ещё не подтверждено
убрать комментарии здесь и дальше по коду  
если хочется что-то неочевидное пояснить, есть javadoc

2022-03-31 09:31 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/repositories/ReviewRepository.java
> +    List<Review> findStudentReview(PlatformUser student);
By не забыл?

2022-03-31 09:34 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/models/Review.java
> +    }
если сделаю класс TimeSlots в пакете models норм будет?

2022-03-31 09:35 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/repositories/ReviewRepository.java
> +    List<Review> findStudentReview(PlatformUser student);
ну задумка в том, что ищем ревью студента/ментора а не ревью по студенту или ментору

2022-03-31 10:22 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +    }
никакой логики в сетерах  
сетеры устанавливают значение

2022-03-31 10:23 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +}
не совсем понятно назначение этого метода
почему он назван set?

2022-03-31 10:24 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/ReviewRestController.java
> +                                                @RequestParam int index) {
зачем смешивать RequestParam и RequestBody ?  
создай себе дто, где все этого замечательным образом объединишь в одну джейсонку  
олсо использовать модельные классы для контрактов контроллера - очень плохая идея

2022-03-31 10:25 UTC, nekromant322 requested changes
Добавить дто и внятно назвать метод

2022-03-31 10:42 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +}
он назначает выбранное время
студент выбирает дату и время, передаёт в запрос,
поле забронированного времени в модели ревью принимает через сеттер LocalDateTime
а таймслоты лежат в листе
поэтому мы извлекаем нужный слот из листа и кладём в LocalDateTime, чтобы потом передать в сеттер поля
возможно стоит поменять название, но я изходил из логики, что мы назначаем время, поэтому set

2022-03-31 10:44 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/rest/ReviewRestController.java
> +                                                @RequestParam int index) {
ок

2022-03-31 10:57 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +}
назвал selectDateTimeSlot

2022-03-31 14:17 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/ReviewDTO.java
> +    private String mentor;
что это за String?

2022-03-31 14:37 UTC, Alexander-Sharipov commented on platform_dto/src/main/java/dtos/ReviewDTO.java
> +    private String mentor;
это для связи ревью с ментором и студентом

2022-03-31 15:00 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/ReviewDTO.java
> +    private String mentor;
это айди чи шо? может отразить это в названии поля? и почему стринг, если айди

2022-03-31 15:03 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/ReviewRestController.java
> +    }
плохая идея доставать вообще все  
они же будут накапливаться  
тогда придется думать над механизмом который их подчищает  
а ваще подчищать не охота, чтоб отслеживать активность по ревью

2022-03-31 17:29 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/ReviewDTO.java
> +    private String mentor;
логин, насколько я понял, но хотелось бы понимать сразу а не пошерстив код

2022-03-31 17:35 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/models/Review.java
> +}
вообще я бы сюда еще прихранил изначальные таймслоты, которые указывал студент, чтоб при смене времени в них "попасть" будучи ментором, а не просто от балды ставить

2022-03-31 17:36 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +    public List<LocalDateTime> generateDefaultDateTimeSlots(LocalDate date) {
как будто бы может быть private

2022-03-31 17:37 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/repositories/ReviewRepository.java
> +    List<Review> findStudentReview(PlatformUser student);
findReviewByMentor на мой вкус должно быть  
не уверен даже, что твой вариант работает

2022-03-31 17:37 UTC, nekromant322 requested changes
Поправить по комментам + накинуть тестов для мапера и сервиса

2022-04-01 07:51 UTC, Alexander-Sharipov commented on platform_dto/src/main/java/dtos/ReviewDTO.java
> +    private String mentor;
добавлю в название логин

2022-04-01 07:52 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/rest/ReviewRestController.java
> +    }
ок, уберу

2022-04-01 07:53 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/models/Review.java
> +}
я тебя понял)

2022-04-01 14:54 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/models/Review.java
> +}
добавил в дто таймслоты, которые выбрал студент, и из которых будет выбирать ментор

2022-04-01 15:46 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/mappers/ReviewMapper.java
> +    private PlatformUserService platformUserService;
зачем это тут?

2022-04-01 15:46 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/mappers/ReviewMapper.java
> +@Builder
+ эти аннотации зачем

2022-04-01 15:46 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        return new ResponseEntity<>("Ревью обновлено!", HttpStatus.OK);
Что-то непонятное, вроде update review, а ты тут сохраняешь его просто, как новое, у тебя же там id в null маппится

2022-04-01 15:46 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        return reviewRepository.findReviewByMentor(mentor);
Хз на сколько такие методы имеют смысл тк спринг разруливает запросы по типу findReviewByUserLogin что-то такое

2022-04-01 15:46 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        return reviewRepository.findReviewByStudent(student);
Аналогично

2022-04-01 16:20 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/ReviewDTO.java
> +    private Boolean confirmed;
поле confirmed как будто излишне
если есть bookedDateTime  - уже можно понять что confirmed  
думаю его стоит и тут и в модели убрать, и опираться на наличие забуканной даты)

2022-04-01 16:20 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/ReviewRestController.java
> +    }
one?  
one, серьезно?  
https://www.google.com/amp/s/habr.com/ru/amp/post/351890/

2022-04-01 16:23 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/ReviewRestController.java
> +    @GetMapping("/mentors")
нейминг в топку что тут, что в следующем
Возможно проще сделать один ендпоинт, который бы принимал фильтр ака:  
{
"mentorId" : 1,  
"studentId" : null,  
"booked" : null
}

2022-04-01 16:23 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/ReviewRestController.java
> +    @GetMapping("/mentors")
и уже искать по полю, если оно не null

2022-04-01 16:25 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/models/Review.java
> +}
я хочу в базе чтоб остались таймслоты которые студенты изначально писал  
чтоб ментор мог поменять время ревью с учетом этих слотов    
дто же ни храняца в базе

2022-04-01 16:26 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/models/Review.java
> +}
да и в целом при апруве ревью надо же чтоб ментор выбрал конкретный слот из тех которые студент изначально обозначил  
а апрув происходит спустя много времени, точно надо слоты хранить

2022-04-03 14:33 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        return reviewRepository.findReviewByMentor(mentor);
если есть такое поле у сущности, насколько я понимаю

2022-04-03 15:14 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        return new ResponseEntity<>("Ревью обновлено!", HttpStatus.OK);
Почему в null? мы же берём данные о сущности из базы и вносим изменения, не меняя при этом id, поэтому в бд сущность с таким же id меняется на новую, разве нет?

2022-04-04 15:14 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        return reviewRepository.findReviewByMentor(mentor);
> если есть такое поле у сущности, насколько я понимаю

Ну ты же юзера достаешь, а потом по юзеру ищешь, почему бы сразу по логину юзера не искать ревью?
1 запрос вместо 2ух

2022-04-04 15:17 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        return new ResponseEntity<>("Ревью обновлено!", HttpStatus.OK);
Моя ошибка, не в тот маппер посмотрел

2022-04-04 17:15 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        return reviewRepository.findReviewByMentor(mentor);
в сущности ревью нет такого поля логинЮзера, там связь с сущностью юзер

2022-04-04 17:22 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        return reviewRepository.findReviewByMentor(mentor);
> в сущности ревью нет такого поля логинЮзера, там связь с сущностью юзер

findReviewByMentorLogin, у юзера есть такое поле, спринг может такое разрулить, посмотри 16 pr, там аналогичная ситуация

2022-04-04 17:56 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        return reviewRepository.findReviewByMentor(mentor);
хм, прикольно

2022-04-06 10:28 UTC, nekromant322 requested changes

2022-04-06 10:28 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/TimeSlotDTO.java
> +    private LocalTime thirdTimeSlot;
почему только три? почему не List?

2022-04-06 10:28 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/TimeSlotDTO.java
> +    private LocalTime bookedTime;
объединить в bookedDataTime

2022-04-06 10:28 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/ReviewRestController.java
> +        }
не уверен, что контроллер - место для такой логики, запихнуть в сервис и написать тесты

2022-04-06 10:30 UTC, Alexander-Sharipov commented on platform_dto/src/main/java/dtos/TimeSlotDTO.java
> +    private LocalTime thirdTimeSlot;
потому что лист не хочет пихать
пишет что низя

2022-04-06 10:31 UTC, Alexander-Sharipov commented on platform_dto/src/main/java/dtos/TimeSlotDTO.java
> +    private LocalTime bookedTime;
нужно именно так, потому что ментор выбирает из времени которое назначил студент, а дату дублировать везде не имеет смысла

2022-04-06 10:31 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/rest/ReviewRestController.java
> +        }
ок

2022-04-06 10:32 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/TimeSlotDTO.java
> +    private LocalTime bookedTime;
оке, убедил

2022-04-06 14:37 UTC, nekromant322 approved these changes

2022-04-06 14:44 UTC, merged