Личный кабинет пользователя платформы Front
nekromant322/platform pull request #48
Opened 2022-04-06 07:33 UTC by TrueMaxWell

Страничка, на которой можно посмотреть информацию о себе
![image](https://user-images.githubusercontent.com/90501949/161920187-4692c0c4-0286-438e-b5d0-d7fe475df9b5.png)

Так же можно добавить/отредактировать
![image](https://user-images.githubusercontent.com/90501949/161920328-7791d9e0-55b0-4e64-8be2-bd8bcce740b7.png)

2022-04-06 08:40 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/models/PersonalData.java
> +    @Column(name = "fullName")
насколько я помню, в бд кэмелКейс не работает, поэтому не лучше ли разделять _?

2022-04-08 07:47 UTC, nekromant322 requested changes

2022-04-08 07:47 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +        PlatformUser account = new PlatformUser(null, login, password, telegramChatId, roles, new PersonalData());
может стоит тестовых данных накинуть, чтоб можно было адекватно генерацию pdf тестировать ?

2022-04-08 07:47 UTC, nekromant322 approved these changes

2022-04-08 07:48 UTC, merged