Фронт бронирования ревью
nekromant322/platform pull request #55
Opened 2022-04-12 10:59 UTC by Alexander-Sharipov

![image](https://user-images.githubusercontent.com/94536519/162945924-1feb60b2-0c35-435d-ba44-753f06b1fabe.png)
при нажатии на кнопку "Запросить ревью" появляется форма запроса, можно добавить дополнительный слот времени
в слоте времени отображается время с интервалом в 30 минут
нельзя отправить запрос без заголовка, без времени и в дату не сегодня и не завтра
при отправке запрашивается подтверждение с выводом информации о ревью
после отправки выводится сообщение, что ревью запрошено, и форма закрывается
![image](https://user-images.githubusercontent.com/94536519/163257796-69c58b5d-ab1a-40dd-b0c4-3b42ce963204.png)
по умолчанию открывается информация о новых ревью
по количеству таймслотов отображаются кнопки accept-ов ревью, при нажатии на выбранное время  запрашивается подтверждение, мол "оно вам надо", если да, то ревью сохраняется за ментором с временем, которое он выбрал
![image](https://user-images.githubusercontent.com/94536519/163257857-570691df-6b5b-4b03-8fbd-b78c9438b148.png)
отображаются вообще все ревью данного ментора
можно отменить ревью (подтверждение прилагается)
![image](https://user-images.githubusercontent.com/94536519/163257902-b0abe3ac-2b0e-4e5f-9c42-eb5e84028980.png)
можно смотреть какие ревью запланированы на сегодня среди всех и если надо, то отжать какое-нибудь ревью себе
или поменять время у своего
![image](https://user-images.githubusercontent.com/94536519/163257932-d8badd01-e152-488b-a868-fdbeb8fe5425.png)
аналогично, только с завтрашним днем

2022-04-12 11:15 UTC, TrueMaxWell commented on platform_orchestrator/src/test/java/com/override/utils/TestFieldsUtil.java
>                  .bookedDate(LocalDate.of(2022, 4, 4))
думаю можно было бы реализовать в InitializationService, создавать эту инфу для наглядности, по аналогии с другими данными которые там генерятся

2022-04-12 11:32 UTC, Alexander-Sharipov commented on platform_orchestrator/src/test/java/com/override/utils/TestFieldsUtil.java
>                  .bookedDate(LocalDate.of(2022, 4, 4))
тоже подумал об этом, но не совсем понял, как вы это делали

2022-04-12 11:44 UTC, TrueMaxWell commented on platform_orchestrator/src/test/java/com/override/utils/TestFieldsUtil.java
>                  .bookedDate(LocalDate.of(2022, 4, 4))
создай подобные методы для различных юзеров, а потом добавь их в @PostConstruct метод

2022-04-12 12:13 UTC, TrueMaxWell commented on platform_orchestrator/src/main/java/com/override/converter/TimeSlotsConverter.java
> +    @Override
camelCase?

2022-04-12 13:14 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/converter/TimeSlotsConverter.java
> +    @Override
его использую при именовании обычных переменных, постоянные именуют таким образом)

2022-04-12 17:58 UTC, scmpsh commented on platform_orchestrator/src/main/resources/static/js/reviewRequestForm.js
> +    const errorDateMessage = "Дата ревью должна быть не позднее сегодня или завтра и не в прошлом";
а может сделать select какой-нибудь на сегодня или завтра? Там ведь отображается целый месяц календарный для выбора даты ревью? Я понимаю, что почти точно никто не записывается на ревью за неделю, но мало ли будут затыкивать все даты до смерти, пока не появится безошибочная

2022-04-12 18:46 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/resources/static/js/reviewRequestForm.js
> +    const errorDateMessage = "Дата ревью должна быть не позднее сегодня или завтра и не в прошлом";
ну вообще, он выведет сообщение, мол не делай так, только сегодня или завтра

2022-04-12 18:46 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/resources/static/js/reviewRequestForm.js
> +    const errorDateMessage = "Дата ревью должна быть не позднее сегодня или завтра и не в прошлом";
но мысль хорошая, подумаю

2022-04-13 23:08 UTC, nekromant322 requested changes

2022-04-13 23:08 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/TimeSlotsConverter.java
> +package com.override.util;
utils - то что можно переиспользовать в разных контекстах, я бы создал папку converter, шоб они все дружно там лежали

2022-04-13 23:08 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
>          reviewRepository.save(reviewMapper.dtoToEntity(reviewDTO,
не понял эту логику
почему мы сетим userLogin в поле менторского логина и студенческого  
жду внятного объяснения, но даже если оно есть - максимально не прозрачная логика, стоит это отразить в javadoc  или зарефакторить

2022-04-13 23:08 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/ReviewRestController.java
> +    public List<ReviewDTO> findReview(@RequestBody ReviewDTO reviewDTO) {
может завести в качестве параметра ReviewFilterDTO?  
прикольно что одна и та же моделька переиспользуется, но часть полей все таки не нужна и это просто не самоочевидно, что тут в качестве фильтра поля юзаются

2022-04-13 23:08 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/mappers/ReviewMapper.java
> +                    .build();
а тебе самому то нравится?  
отрефачить, убрать дублирование

2022-04-13 23:08 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/mappers/ReviewMapper.java
> +        return dtoList;
не стоит так делать  
для кого изобрели стримы?  

для любой коллекцией Review list.stream.map(ReviewMapper::entityToDto).collect(Collectors.toList())

2022-04-13 23:08 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/mappers/ReviewMapper.java
> +        return dtoList;
метод убрать к чертям собачим
при необходимости вполне подойдет решение в одну строку по месту)

2022-04-13 23:08 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/models/Review.java
> +    private String topic;
зачем указывать имя колонки?

2022-04-13 23:08 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +            return reviewMapper.entitiesToDto(reviewRepository.findReviewByMentorLogin(reviewDTO.getMentorLogin()));
Добавить джавадок с пояснением что тут происходит (ну и заменить аргумент на объект фильтра)

2022-04-13 23:09 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/utils/TestFieldsUtil.java
>                  .bookedDate(LocalDate.of(2022, 4, 4))
не очень понял про что тред, это же ютильный метод генерации объекта для тестов

2022-04-13 23:09 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/utils/TestFieldsUtil.java
>                  .bookedDate(LocalDate.of(2022, 4, 4))
Инициализацию тестовыми данными при старте контекста в InitializationService докинуть, эт дело хорошее

2022-04-14 10:49 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
>          reviewRepository.save(reviewMapper.dtoToEntity(reviewDTO,
студент запрашивает ревью, но его логин при этом не прописывается в запросе

2022-04-14 10:56 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/resources/static/js/reviewRequestForm.js
> +    const errorDateMessage = "Дата ревью должна быть не позднее сегодня или завтра и не в прошлом";
не получилось сделать так, чтобы изначально можно было выбрать только сегодня или завтра
в телеграм боте при запросе ревью написано, чтобы выбирали дату сегодня или завтра
пропишу дополнительно тоже это, но вообще календарь открывается автоматически на сегодняшней дате

2022-04-17 22:27 UTC, nekromant322 approved these changes

2022-04-17 22:27 UTC, merged