Feature/student progress
nekromant322/platform pull request #58
Opened 2022-04-17 18:12 UTC by TrueMaxWell

Прогресс студента по урокам.
В модель была добавлена коллекция, содержащая в себе список пройденных уроков.
Урок считается пройденным когда студент переходит на следующий урок по нажатию соответствующей кнопки (по нажатию переходит к следующему уроку.
![image](https://user-images.githubusercontent.com/90501949/163726916-9fdb3a1d-a6ec-4fe4-9099-4d1724f4277c.png)

После чего в лист добавляется полное название урока в формате "course-chapter-step-lesson"
![image](https://user-images.githubusercontent.com/90501949/163726995-ebfe61bf-8485-4e7c-b8ab-978c7ccb7c6e.png)

В навигационной панели для переключения между уроками пройденные так же помечаются (на данный момент меняется цвет на зеленый), так же в случае если все уроки данного этапа были пройдены, то и этап так же окрашивается.
![image](https://user-images.githubusercontent.com/90501949/163727088-c7efef5e-5b1c-4ecb-9186-a256c7de8dc9.png)

2022-04-17 22:29 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/LessonProgressService.java
> +        AtomicBoolean exists = new AtomicBoolean(false);
а зачем тут AtomicBoolean?

2022-04-17 22:31 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +        accountRepository.save(platformUser);
гоу accountRepository -> PlatformUserRepository  
после ренейминга сущности дао чет осталась старой, лучше бы они совпадали

2022-04-17 22:32 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/LessonProgressService.java
> +        AtomicBoolean exists = new AtomicBoolean(false);
как на счет написать тесты для этого сервиса?

2022-04-17 22:32 UTC, nekromant322 requested changes
нужны минорные чейнджи + тесты

2022-04-17 22:39 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/service/LessonProgressServiceTest.java
> +        assertEquals(platformUser.getLessonProgress(), lessons);
что проверяет этот тест?  
зачем мы вызываем `PlatformUserService`? это же мок

2022-04-17 22:39 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/service/LessonProgressServiceTest.java
> +    }
аналогично

2022-04-17 22:39 UTC, nekromant322 requested changes
Допилить тесты

2022-04-18 14:59 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/models/PlatformUser.java
> +    @LazyCollection(LazyCollectionOption.FALSE)
совсем не нравится, то что каждый раз когда надо достать пользователя из базы загружается еще огромное кол-во записей  
Я бы развернул связь в отдельную модельку

2022-04-27 06:56 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/models/LessonProgress.java
> +    @Column(name = "id")
эта аннотация по идее не нужна, её заменяет @Id

2022-04-27 06:59 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/repositories/LessonProgressRepository.java
> +    List<LessonProgress> findAllByUserId (Long id);
findAllByUserId(Long id) без пробела и смотрится лучше

2022-04-27 18:03 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/models/PlatformUser.java
> +import java.util.Map;
зачем это тут?

2022-04-27 18:05 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/LessonProgressService.java
> +    }
Напиши javadoc с пояснением че тут происходить  
и название метода я бы еще сменил  
check - это проверка, а ты ничего не проверяешь  
я понял аналогию с чекбокосом, но она весьма туманная

2022-04-28 11:02 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/LessonProgressService.java
> + */
это скорее над методом надо, над классом пишут описание класса и зачем нужен

2022-04-28 21:03 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/LessonProgressService.java
> +     * тем самым "помечает" его как пройденный.
->
@param student - пользователь платформы
@param lesson - идентификатор урока в формате "core-1-1" 
  указанный lesson вносится в коллекцию с пройдеными уроками, тем самым "помечает" его как пройденный.

2022-04-28 21:04 UTC, nekromant322 approved these changes, later dismissed

2022-04-28 22:00 UTC, nekromant322 approved these changes

2022-04-28 22:01 UTC, merged