Feature/notification-call-code
nekromant322/platform pull request #6
Opened 2022-02-02 14:05 UTC by free2fqn

Добавил функционал для верификации номера. На контроллер посылается запрос с текстом номера в формате "7*********" (как я понял можно даже и не 7, просто для других стран чуть дороже). Контроллер возвращает код безопасности для верификации, а ответ сервиса sms.ru печатает в консоль (удобно, что бы отслеживать баланс и стоимость).

2022-02-03 07:59 UTC, nekromant322 requested changes

2022-02-03 07:59 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/controllers/CodeCallController.java
> +    CodeCallController(CodeCallService codeCallService) {
public?

2022-02-03 07:59 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/CodeCallService.java
> +    String sendGet(String clientPhoneNumber);
verifyNumber?

2022-02-03 07:59 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/controllers/CodeCallController.java
> +    @GetMapping("/codecall")
camelCase?

2022-02-03 07:59 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/CodeCallServiceImpl.java
> +    CodeCallServiceImpl(RestTemplate restTemplate, ObjectMapper objectMapper) {
public?

2022-02-03 08:01 UTC, nekromant322 requested changes

2022-02-03 08:01 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/CodeCallServiceImpl.java
> +            e.printStackTrace();
так не пойдет, пусть отлетает 500 от сервера

2022-02-03 08:01 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/CodeCallServiceImpl.java
> +        String securityCode = "-1";
эм?

2022-02-03 08:27 UTC, free2fqn commented on platform_notification/src/main/java/com/override/controllers/CodeCallController.java
> +    CodeCallController(CodeCallService codeCallService) {
@nekromant322 Зачем? 0о

2022-02-03 08:31 UTC, free2fqn commented on platform_notification/src/main/java/com/override/service/CodeCallService.java
> +    String sendGet(String clientPhoneNumber);
fixed

2022-02-03 08:31 UTC, free2fqn commented on platform_notification/src/main/java/com/override/controllers/CodeCallController.java
> +    @GetMapping("/codecall")
fixed

2022-02-03 08:33 UTC, free2fqn commented on platform_notification/src/main/java/com/override/service/CodeCallServiceImpl.java
> +        String securityCode = "-1";
идея была в том, что бы -1 была заглушкой и мы сразу понимали, что секьюрити код нормально не сгенерился

2022-02-03 08:37 UTC, free2fqn commented on platform_notification/src/main/java/com/override/controllers/CodeCallController.java
> +    CodeCallController(CodeCallService codeCallService) {
fixed

2022-02-03 08:37 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/CodeCallServiceImpl.java
> +        String securityCode = "-1";
идея хуевая

2022-02-03 08:37 UTC, free2fqn commented on platform_notification/src/main/java/com/override/service/CodeCallServiceImpl.java
> +    CodeCallServiceImpl(RestTemplate restTemplate, ObjectMapper objectMapper) {
fixed

2022-02-03 09:21 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/service/CodeCallServiceImpl.java
> +        System.out.println(response.getBody());
убрать

2022-02-03 09:23 UTC, nekromant322 commented
заменить  restTemplate на фейн

2022-02-03 12:29 UTC, free2fqn commented on platform_notification/src/main/java/com/override/service/CodeCallServiceImpl.java
> +        String securityCode = "-1";
fixed

2022-02-03 12:30 UTC, free2fqn commented on platform_notification/src/main/java/com/override/service/CodeCallServiceImpl.java
> +        System.out.println(response.getBody());
fixed

2022-02-03 12:34 UTC, free2fqn commented
Заменил на Feign

2022-02-03 14:56 UTC, nekromant322 requested changes

2022-02-03 14:56 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/controller/CodeCallController.java
> +@RestController
тут бы добавить мапинг какой-то, а то из корня торчит /codeCall и /balance  
я бы добавил /calls или что-то вроде того

2022-02-03 14:56 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/feign/SmsRuFeign.java
> +    String verifyPhone(@PathVariable String phone, @PathVariable String apiID);
почему сразу не получать СodeCallResponseDTO?  
`СodeCallResponseDTO verifyPhone(@PathVariable String phone, @PathVariable String apiID);`

2022-02-03 14:56 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/feign/SmsRuFeign.java
> +    String getBalance(@PathVariable String apiID);
аналогично

2022-02-03 14:58 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/feign/SmsRuFeign.java
> +    String verifyPhone(@PathVariable String phone, @PathVariable String apiID);
`@Pathvariable` не совсем корретно, можно юзать `@RequestParam("phone")`, тогда параметры сами к итоговой строке гет запроса добавится, а `@GetMapping("/code/call")`

2022-02-04 10:04 UTC, free2fqn commented on platform_notification/src/main/java/com/override/feign/SmsRuFeign.java
> +    String getBalance(@PathVariable String apiID);
Здесь я считаю лучше оставить @PathVariable, иначе придется добавлять второй аргумент для флага json=1. Методом getBalance станет не так удобно пользоваться

2022-02-04 13:04 UTC, nekromant322 commented on platform_notification/src/main/java/com/override/feign/SmsRuFeign.java
> +    String getBalance(@PathVariable String apiID);
вполне удобно, в сервисе будет константа с говорящим названием, которую при желании можно будет поменять

2022-02-05 13:05 UTC, nekromant322 approved these changes

2022-02-05 13:22 UTC, merged