(WIP) Document size limit
nekromant322/platform pull request #65
Opened 2022-05-01 10:21 UTC by Alexander-Sharipov

2022-05-01 17:18 UTC, nekromant322 commented on platform_orchestrator/src/main/resources/application.yml
>  cache:
# в мегабайтах
fileSize:
personalDataDocument: 5
dogovorObOkazaniiUslug : 10

2022-05-01 17:18 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/PersonalDataRestController.java
> +            // не загружать, выдать ошибку превышения размера файла
return new ResposnseBody<>()

2022-05-02 14:07 UTC, nekromant322 submitted a review, later dismissed

2022-05-03 13:27 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/DocumentRestController.java
> +                           @Value("${documentSizeLimit.forPersonalData}") long maxFileSize)
Почему не внедрить это в сервисе?  
голосую за то чтоб перенести

2022-05-03 13:28 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/DocumentRestController.java
> +            @AuthenticationPrincipal CustomStudentDetailService.CustomStudentDetails user) {
?

2022-05-03 13:28 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/DocumentService.java
> +    public void uploadFile(MultipartFile file, String login, long maxFileSize) throws FileUploadException {
убрать аргумент, соответственно

2022-05-03 13:29 UTC, nekromant322 requested changes
немножк порефакторить внедрение макс размера

2022-05-03 13:49 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/rest/DocumentRestController.java
> +            @AuthenticationPrincipal CustomStudentDetailService.CustomStudentDetails user) {
ну так смотрится лучше

2022-05-03 13:50 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/rest/DocumentRestController.java
> +                           @Value("${documentSizeLimit.forPersonalData}") long maxFileSize)
сервис потому что универсальный для всех, а конкретно для персоналДата свой ендпоинт
иначе придется каждый раз в серсиве новый метод фигачить под каждое ограничение

2022-05-03 15:23 UTC, nekromant322 requested changes
А где тесте с загрузкой слишком большого файла?

2022-05-03 15:23 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/DocumentRestController.java
> +    public List<Document> getAllFilesInfoForCurrentUser(@AuthenticationPrincipal CustomStudentDetailService.CustomStudentDetails user) {
А  не жирно ли возвращать целиком файлы? Мб дтошку с названием и айдишником? А по ацдишнику уже скачать конкретно тот что хочешь можно будет

2022-05-03 15:27 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/rest/DocumentRestController.java
> +    public List<Document> getAllFilesInfoForCurrentUser(@AuthenticationPrincipal CustomStudentDetailService.CustomStudentDetails user) {
это лучше в следующем пр исправить, потому что рест удалится, а обычный появится

2022-05-03 16:07 UTC, nekromant322 approved these changes

2022-05-03 16:08 UTC, merged