Отчет о собеседованиях
nekromant322/platform pull request #69
Opened 2022-05-04 19:18 UTC by Alexander-Sharipov

2022-05-06 10:54 UTC, scmpsh commented on platform_orchestrator/src/main/resources/static/js/interviewReport.js
> +        offerBtn.type = "submit";
название кнопки не поменял на русское?

2022-05-06 10:54 UTC, scmpsh commented on platform_orchestrator/src/main/resources/static/js/interviewReport.js
> +        acceptedBtn.type = "submit";
тоже название кнопки

2022-05-06 11:25 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/resources/static/js/interviewReport.js
> +        offerBtn.type = "submit";
Вообще изначально думал, что по-английски будет унисекс, но потом вспомнил, что можно приписать (а) в конце и будет шоколадно, так что перевёл на русский

2022-05-06 11:26 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/resources/static/js/interviewReport.js
> +        acceptedBtn.type = "submit";
и здесь тоже
даже названия колонок в таблице поменял на русский

2022-05-07 23:59 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/InterviewReportDTO.java
> +    private String userLogin;
лишнее, нам и так известно какой пользователь делает запрос

2022-05-08 00:00 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/InterviewReportDTO.java
> +    private String status;
статус тоже передавать не нужно, в модельку по умолчанию проставляем первый статус в цепочке

2022-05-08 00:01 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/InterviewReportService.java
> +    public void saveInterviewReport(InterviewReportDTO interviewReportDTO) {
нейминг потрясающий 
как неожиданно для метода в классе InterviewReportService, что он сохраняет interviewReport

2022-05-08 00:01 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/InterviewReportService.java
> +                .map(interviewReportMapper::entityToDto).collect(Collectors.toList());
аналогично

2022-05-08 00:02 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +    public Role checkPlatformUserRole(HttpServletRequest request) {
может get? check чаще подразумевает булевый результат, либо check в смысле отметить пункт в списке

2022-05-08 00:03 UTC, nekromant322 requested changes
Убрать лишние данные из дтошек и поработать над неймингом
слегка поменять фронт

2022-05-08 06:35 UTC, Alexander-Sharipov commented on platform_dto/src/main/java/dtos/InterviewReportDTO.java
> +    private String userLogin;
пользователь привязывается на фронте, а оттуда уже отправляется на бэк
если привязывать на бэке, то когда админ будет менять статус, то поменяется и юзер

когда мы возвращаем с базы, то передаем дто, без этого поля не будет и колонки с логином в таблице

2022-05-08 06:37 UTC, Alexander-Sharipov commented on platform_dto/src/main/java/dtos/InterviewReportDTO.java
> +    private String status;
статус тоже меняется на фронте
иначе придется передавать новый статус, зп и айди, искать по айди отчет, сетить иму новые поля и возвращать обратно, куча новых методов

2022-05-09 08:51 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
> +import org.springframework.web.bind.annotation.RestController;
отличный чейндж, люблю такие

2022-05-09 08:52 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/InterviewReportRestController.java
> +    @PatchMapping("/Offer")
почему с большой буквы?

2022-05-09 08:52 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/InterviewReportRestController.java
> +    @PatchMapping("/Accepted")
почему с большой буквы?

2022-05-09 08:52 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
> +import org.springframework.web.bind.annotation.RestController;
это он сам, когда импорты оптимизировал

2022-05-09 08:52 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/InterviewReportService.java
> +    public void update(InterviewReportUpdateDTO interviewReportUpdateDTO, String status) {
сделать статус енамом, а не стрингой

2022-05-09 08:53 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/rest/InterviewReportRestController.java
> +    @PatchMapping("/Offer")
так удобнее

2022-05-09 08:54 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/rest/InterviewReportRestController.java
> +    @PatchMapping("/Accepted")
статусы с большой буквы сохраняются
на фронте общий метод, который принимает статус в качестве аргумента и добавляет его в урл

2022-05-09 08:55 UTC, nekromant322 requested changes
дто отчета обрезать малость и изобрести енам со статусами, поправить нейминг

2022-05-10 18:58 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
> -import org.springframework.web.bind.annotation.RestController;
не трогай файлы, которые не редачишь, зачем я смотрю это в ПРах?

2022-05-10 18:59 UTC, nekromant322 approved these changes

2022-05-10 19:07 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/rest/QuestionRestController.java
> -import org.springframework.web.bind.annotation.RestController;
![image](https://user-images.githubusercontent.com/94536519/167703764-0a93420c-74b8-46d5-b861-226e3769df64.png)
ну как бы

2022-05-10 19:08 UTC, merged