number of reports fix
nekromant322/platform pull request #73
Opened 2022-05-14 16:53 UTC by yusov8400

крайние отчеты будут создаваться за два дня до текущего дня
то есть на сегодняшнюю дату 14.05 крайний отчет создается на 11 число

2022-05-14 17:36 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
>          LocalDate startDate = LocalDate.of(2022, 1, 1);
если я правильно понял логику метода, то на каждого юзера (коих 5) будет создаваться по отчету в день начиная отсюда и заканчивая позавчера. Не довига ли записей для тестовых данных? может ограничить старт месяцем или неделей там? типа LocalDate.now().minusWeek(1) (вроде есть такое)

2022-05-15 00:47 UTC, nekromant322 requested changes
Очень много отчетов, и с каждным днем инициализация будет все дольше
Давай каждому студенту 5 отчетов за последние 10 дней

2022-05-16 20:55 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +        long randomDay = ThreadLocalRandom.current().nextLong(minDay, maxDay);
зачем такой сложный рандом? че он делает по сравнению с new Random()?

2022-05-16 20:56 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +        long randomDay = ThreadLocalRandom.current().nextLong(minDay, maxDay);
это код можно упростить до `LocalDate.now().minusDays(12).toEpochDay() + nextInt(12)`

2022-05-16 21:01 UTC, nekromant322 approved these changes

2022-05-17 22:27 UTC, merged