add Date in creating a report
nekromant322/platform pull request #74
Opened 2022-05-15 00:30 UTC by yusov8400

при создании отчета теперь указывается по умолчанию сегодняшняя дата

2022-05-15 00:48 UTC, nekromant322 commented on platform_orchestrator/src/main/resources/templates/report.html
> +    <input class="input" type="date" id="datePicker" th:required="required"/>
а зачем менять айдишник? отправка после таких выкрутасов будет работать? там же наверняка отправка на бэк идет данных, которые по айдишнику `report-date` тащаться

2022-05-15 00:49 UTC, nekromant322 requested changes
Проверить работает ли сохранение отчетов (посмотреть в базе)

2022-05-15 07:33 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/resources/templates/report.html
> +    <input class="input" type="date" id="datePicker" th:required="required"/>
Спойлер: не будет, потому что тут то айди поменял, а в коде выше нет
стало быть код выше запрашивает инпут поле даты у айди, которого теперь нет

2022-05-15 07:38 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/resources/static/js/report.js
> +document.getElementById('datePicker').valueAsDate = new Date();
не уверен, что такая функция будет работать сама по себе, но это смотреть надо, когда редачишь фронт)
возможно имеет смысл ещё вынести дату в отдельную переменную и вызывать у неё потом getDate() or getTime()

2022-05-16 20:54 UTC, nekromant322 approved these changes

2022-05-17 21:49 UTC, merged