WIP Feature/bug reports
nekromant322/platform pull request #75
Opened 2022-05-20 23:19 UTC by yusov8400

Work in progress

2022-05-25 12:58 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/BugReportsDTO.java
> +    private String type;
что значит type? если type, то мне хочется видеть enum  
хотя я в целом не понимаю о каких типах речь

2022-05-25 12:59 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/BugReportController.java
> +        return "redirect:http://localhost:8000";
как ты мне предлагаешь такой в продакшн выкатывать?

2022-05-25 13:00 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/BugReportController.java
> +@Controller
->RestController  
попробуй отправлять файлики джсом, а не через формочку

2022-05-25 13:00 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/BugReportController.java
> +@Controller
тогда метод ниже можно будет тоже рестовым сделать, и не бахать @ResponseBody

2022-05-25 13:00 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/BugReportController.java
> +    public String uploadScreen(@AuthenticationPrincipal CustomStudentDetailService.CustomStudentDetails user,
screen?

2022-05-25 13:01 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/BugReportService.java
> +            bug.setName(file.getOriginalFilename());
-> builder

2022-05-25 13:02 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/BugReportService.java
> +            e.printStackTrace();
можно как-то все таки обработать? или дать ошибке вылететь и всему поломаться?   
в твоем варианте пользователь загрузит хреновую картинку, на бэке она не прочитается, но все как будто бы окей  
и баг репорт потеряется

2022-05-25 13:03 UTC, nekromant322 commented on platform_orchestrator/src/main/resources/application.yml
> +    - баги
`Баги`

2022-05-25 13:04 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/BugReportService.java
> +    public List<BugReportsDTO> getAll(String login) {
а зачем искапать баг репорты по логину, не очень понял

2022-05-25 13:04 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/BugReportService.java
> +        }
вынести в отдельнный класс (ака маппер)

2022-05-25 13:12 UTC, nekromant322 requested changes
Порефакторить + пояснить за типы

2022-05-25 14:02 UTC, yusov8400 commented on platform_dto/src/main/java/dtos/BugReportsDTO.java
> +    private String type;
имелось ввиду тип файла например png или же jpeg

2022-05-30 12:44 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/BugReportController.java
> +    @MaxFileSize("${documentSizeLimit.forPersonalData}")
тут отдельную пропертю надо завести, это не personalData файлы, это documentSizeLimit.bugReports

2022-05-30 12:44 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/BugReportController.java
> +    public List<BugReportsDTO> getAllFilesInfoForCurrentUser() {
точно `getAllFilesInfoForCurrentUser` ?

2022-05-30 13:43 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/AdminPageController.java
> +    public  String check(){
почему чек? allBugsPage?

2022-05-31 18:01 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/resources/static/js/header.js
>      html += "<li class=\"nav-item\">\n<button class=\"button__bugReports\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">сообщить об ошибке</button>\n</li>";
"сообщить" с большой буквы бы...

2022-05-31 18:02 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/resources/templates/fragments/navbar.html
> +                    <h5 class="modal-title" id="exampleModalLabel">опишите проблему</h5>
тут тоже с большой буквы бы

2022-05-31 18:02 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/resources/templates/fragments/navbar.html
> +                                          placeholder="введите описание проблемы" rows="1" maxlength="255"
и тут

2022-05-31 18:57 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/BugReportService.java
> +            }
прелесть билдер в том, что это условие можно не писать  
убрать условие (грамотно разменеджить NPE, если вдруг будет вылетать)

2022-05-31 18:58 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/BugReportService.java
> +            }
грамотно можно с Optional, например  
а можно
.content(file.isEmpty() ? null : file.getBytes())

2022-05-31 18:59 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/BugReportService.java
> +    }
попробуй стримом (не обязательно, но было бы прикольно)

2022-05-31 18:59 UTC, nekromant322 reviewed
починить нейминг, сделать рестовым  
мелочные правки по остальному

2022-05-31 19:00 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/AdminPageController.java
> +    public  String AllBugsPage(){
с маленькой буквы метод

2022-05-31 19:01 UTC, yusov8400 commented
![Screenshot_141](https://user-images.githubusercontent.com/92119648/171263259-e67adbad-f532-41b3-b6f6-54cbac7e2639.png)
появилась большая красная кнопка,при нажатии на нее вылезает модалка
![Screenshot_142](https://user-images.githubusercontent.com/92119648/171263574-fcdcd6a9-96c5-4fcc-8bf4-54119524e763.png)
в которой можно описать свою проблему и опционально прикрепить скрин
![Screenshot_143](https://user-images.githubusercontent.com/92119648/171264046-a5cd1b3e-47b0-4876-be66-bc93228675f9.png)
Админ может просматривать все присланные баги и скачивать скриншот если такой имеется

2022-06-03 20:32 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/BugReportRestController.java
> +    @PostMapping("")
-> `@PostMapping`

2022-06-03 20:32 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/BugReportRestController.java
> +    @GetMapping("")
аналогично

2022-06-03 20:33 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/BugReportService.java
> +                        .type(file.isEmpty() ? "text" : file.getContentType())
что за "text" ?

2022-06-03 20:33 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/BugReportService.java
> +                        .name(file.isEmpty() ? "-" : file.getOriginalFilename())
тоже не понял эту магическую константу

2022-06-03 20:33 UTC, nekromant322 requested changes
последние правочки и мержу

2022-06-04 11:45 UTC, nekromant322 approved these changes

2022-06-04 11:59 UTC, merged