add endpoint for init  with  test data
nekromant322/platform pull request #78
Opened 2022-06-11 18:59 UTC by yusov8400

добавлен ендпоинт для инициализации тестовыми данными
теперь при запуске платформы инициализируется только админ,а при переходе на ендпоинт уже все тестовые данные

2022-06-11 21:04 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/InitializationController.java
> +@RequestMapping("init")
добавь чтоб этот ендпоинт только в профиле dev работал  
для профиля prod он не нужен

2022-06-11 21:05 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/InitializationController.java
> +    InitializationService initializationService;
-> private

2022-06-11 21:06 UTC, nekromant322 requested changes
минорные чейнджи и можно мержить

2022-06-12 12:10 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/InitializationController.java
> +        return "redirect:http://localhost:8000/";
а если порт поменяется? где-нибудь в пропертях

2022-06-12 22:03 UTC, nekromant322 approved these changes

2022-06-13 08:42 UTC, merged