Notification before review
nekromant322/platform pull request #79
Opened 2022-06-14 16:40 UTC by TrueMaxWell

Eведомление всем участникам (студенту и ментору) за 5 минут до начала ревью в тг .

2022-06-14 22:36 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +    }
вынести только этот метод в отдельный пакет в класс ReviewScheduler  
олсо неплохо бы в документации пояснить за шедулер, почему именно такие кроны

2022-06-14 22:37 UTC, nekromant322 requested changes
рефакторинг + дока

2022-06-14 22:40 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +            if (review.getBookedTime() != null && review.getBookedTime().equals(LocalTime.now().plusMinutes(5))) {
я бы не делал такую строгую проверку, потому что если за время выполнения этого кода тикнет 56 или 26 минута, то нотификейшн не отправится, лучше интервалом ака isBefore isAfter

2022-06-15 10:58 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        for (Review review : todayReviewList) {
stream?

2022-06-15 11:03 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        for (Review review : todayReviewList) {
мы думали над этим сначала, но нам ведь кучу условий надо запихнуть

2022-06-15 20:05 UTC, nekromant322 requested changes
тесты

2022-06-17 12:57 UTC, nekromant322 approved these changes

2022-06-17 14:59 UTC, merged