add file size test
nekromant322/platform pull request #8
Opened 2022-02-07 15:42 UTC by kemenchik

2022-02-08 01:38 UTC, nekromant322 approved these changes, later dismissed
ну допустим, только идею не совсем понял  
зачем проверка и почему именно на два мегабайта?  
почему магическими константами ? -_- как они выбраны?
@kemenchik

2022-02-08 07:01 UTC, kemenchik commented
> 

На платформах обычно есть ограничение по времени и месту, вроде, как я понял, время там учитывается, а вот на место нужно проверить, на степике 64 мб, но это что-то слишком много, наш класс на эту задачу весит 0,5. Взял просто немного с запасом. Константу вынесу

2022-02-08 12:23 UTC, nekromant322 commented
> > 
> 
> На платформах обычно есть ограничение по времени и месту, вроде, как я понял, время там учитывается, а вот на место нужно проверить, на степике 64 мб, но это что-то слишком много, наш класс на эту задачу весит 0,5. Взял просто немного с запасом. Константу вынесу 
> @nekromant322 

Может стоит написать общее ограничение для всех задач и не микроменджментить?

2022-02-08 13:39 UTC, kemenchik commented
> > > 
> > 
> > 
> > На платформах обычно есть ограничение по времени и месту, вроде, как я понял, время там учитывается, а вот на место нужно проверить, на степике 64 мб, но это что-то слишком много, наш класс на эту задачу весит 0,5. Взял просто немного с запасом. Константу вынесу
> > @nekromant322
> 
> Может стоит написать общее ограничение для всех задач и не микроменджментить?

Звучит логично

2022-02-09 03:15 UTC, nekromant322 requested changes

2022-02-09 03:15 UTC, nekromant322 commented on platform_dto/src/main/java/enums/Status.java
> +    OUT_OF_MEMORY,
OUT_OF_SPACE?  
OOM все таки про другое

2022-02-09 03:15 UTC, nekromant322 commented on platform_code_executor/src/main/java/com/override/service/test/AbstractTaskTest.java
> +        }
вынести в отдельный метод

2022-02-09 22:33 UTC, nekromant322 requested changes
оптимизировать (знатно)

2022-02-09 22:33 UTC, nekromant322 commented on platform_code_executor/src/main/java/com/override/service/test/AbstractTaskTest.java
> +        testResults.add(getSpaceTestResult());
это очень нелогично  
сначала компилируем тратя дофига времени, потом проверяем размер файла  
даже если размер нас не устраивает прогоняем все тест кейсы, и только потом выдает ошибку превышенного размера  
О - оптимизация

2022-02-10 07:39 UTC, kemenchik commented on platform_code_executor/src/main/java/com/override/service/test/AbstractTaskTest.java
> +        testResults.add(getSpaceTestResult());
А зачем хранить тогда результаты кейсов вообще? Почему не возвращать первый не пройденный?

2022-02-10 17:30 UTC, nekromant322 commented on platform_code_executor/src/main/java/com/override/service/test/AbstractTaskTest.java
> +        testResults.add(getSpaceTestResult());
потому что я ахуел от ада эксепшонов, с помощью которого это можно сделать  
ну а вообще хотел выводить потом еще 
Test 1 passed
Test 2 passed и тд

2022-02-28 21:46 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/CodeTryController.java
> +            throw new IllegalArgumentException("Введенный код некорректен (не прошел по памяти)");
ваще не понятное сообщение! ощущение что дроп по OOM

2022-03-01 12:40 UTC, closed without merging

2022-03-01 12:41 UTC, nekromant322 commented
сделали как надо в другом ПР