Feature/salary stat
nekromant322/platform pull request #81
Opened 2022-06-17 16:04 UTC by yusov8400

реализовал отображение графика зарплат при принятом оффере

![Screenshot_154](https://user-images.githubusercontent.com/92119648/174336158-e7aa0b8e-212e-4945-a03b-dcea1c2e8e5a.png)

2022-06-17 17:24 UTC, Alexander-Sharipov commented
Сделай график разноцветным

2022-06-17 17:25 UTC, TrueMaxWell commented on platform_orchestrator/src/main/java/com/override/service/StatisticsService.java
> +    public SalaryDTO getSalaryStatistics() {
// убери

2022-06-17 17:25 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/repositories/SalaryRepository.java
> +public interface SalaryRepository  extends JpaRepository<InterviewReport, Long> {
не совсем понятно, зачем создавать отдельную репу, когда можно расширить уже существующую?

2022-06-17 17:26 UTC, TrueMaxWell commented on platform_dto/src/main/java/dtos/SalaryStatDTO.java
> +    private Integer borderWidth;
почему data, может быть не совсем понятно что это из себя представляет, можно подумать над неймингом

2022-06-17 17:27 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/rest/StatisticsRestController.java
> +    public SalaryDTO salaryStat(){
метод скорее следует назвать getSalaryStat() ну или как-то так, названия методов обычно начинаются с глагола

2022-06-17 17:27 UTC, TrueMaxWell commented on platform_orchestrator/src/main/resources/static/js/statistics.js
> +//var ctxSalary = document.getElementById('salaryChart').getContext('2d');
закоменченные строки

2022-06-17 17:27 UTC, TrueMaxWell commented on platform_orchestrator/src/main/resources/static/js/statistics.js
> +//         responsive: true,
и тут тоже

2022-06-17 17:40 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/resources/static/js/statistics.js
> +        url: "/statistics/salaryStat",
"/statistics/salary" - итак понятно, что статистика по зарплате, повторять не нужно)

2022-06-17 17:43 UTC, Alexander-Sharipov commented
есть вопросы к неймингу (по всему коду), лично я не сразу вник что к чему, хотя возможно я придираюсь)
и тесты добавь

2022-06-18 20:09 UTC, nekromant322 commented on platform_dto/src/main/java/dtos/SalaryStatDTO.java
> +    private Integer borderWidth;
я бы тоже поменял нейминг  
в жсе просто дтошку принять и в график уже как data засунуть

2022-06-18 20:10 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/mappers/SalaryStatMapper.java
> +public class SalaryStatMapper {
можно подумать над тем чтоб сделать в рамках InterviewReportMapper

2022-06-18 20:11 UTC, nekromant322 requested changes
полечить конфликты + рефакторинг по комментам

2022-06-19 19:45 UTC, nekromant322 submitted a review, later dismissed

2022-06-19 20:18 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/StatisticsService.java
> +                                salary.getDate().getMonthValue() == label.getMonthValue())
Не уверен уместно ли тут ==, мб equals использовать?

2022-06-19 20:25 UTC, Alexander-Sharipov commented on platform_orchestrator/src/test/java/com/override/utils/TestFieldsUtil.java
> +    public static List<InterviewReport> generateReportsList() {
лучше укажи явно InterviewReport, в проекте несколько репортов есть
а вообще листы лучше создавать на месте, потому что в разных случая могут пригодится разные листы
тут у тебя просто три одинаковых отчета

2022-06-19 20:29 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/repository/SalaryRepository.java
> +public interface SalaryRepository  extends JpaRepository<InterviewReport, Long> {
кажется ты забыл удалить теперь уже ненужную репу, ну или в коммит добавить

2022-06-20 15:08 UTC, yusov8400 commented on platform_orchestrator/src/main/java/com/override/service/StatisticsService.java
> +                                salary.getDate().getMonthValue() == label.getMonthValue())
equals здесь не подойдет так как здесь мне надо сравнивать год и месяц ,а методы getYear() и getMonthValue() возвращают int

2022-06-21 00:40 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/repository/SalaryRepository.java
> +public interface SalaryRepository  extends JpaRepository<InterviewReport, Long> {
удаляй репо и смержим

2022-06-21 00:41 UTC, nekromant322 approved these changes

2022-06-21 00:41 UTC, merged