renamed packages
nekromant322/platform pull request #85
Opened 2022-06-21 20:53 UTC by seenister

Переименовала пакеты из мн. числа в ед. число

2022-06-21 23:08 UTC, nekromant322 requested changes
а как на счет в самих файликах заменить первую строчку (package bla.bla.bla.feign) ну и импорты, автоматический ренейминг идеи в помощь)

2022-06-21 23:08 UTC, nekromant322 commented on .gitignore
> +customClass/**
это можно не трогать, откати, это генерируемые файлики (на самом деле их вообще из реы надо удалять, на аккуратно, просто пока не трогай)

2022-06-22 17:12 UTC, seenister commented on .gitignore
> +customClass/**
Окей, с customClasses поняла. Сейчас доработала ренейминг и запустила проект. Сейчас должно быть правильно.

2022-06-22 23:25 UTC, nekromant322 approved these changes

2022-06-23 08:16 UTC, merged