Fix learning status
nekromant322/platform pull request #86
Opened 2022-06-21 22:38 UTC by Alekshas

Добавил статусы пользователям, добавил метод в контроллере, изменил тесты. Отрефакторил таблицу, создал попАп форму, добавил кнопки, добавил сортировку.

2022-06-22 00:29 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +        if(status){
add space

2022-06-22 00:29 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +        }else {
-//-

2022-06-22 16:12 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +        }else {
Исправил

2022-06-22 16:13 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +        if(status){
добавил

2022-06-22 23:20 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/model/enums/StatusUser.java
> +package com.override.model.enums;
в модуле dto есть папка enums, чтоб статусы можно было извне использоват (врядли конкретно тут понадобится, но просто так единообразнее будет)

2022-06-22 23:22 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/model/enums/StatusUser.java
> +public enum StatusUser{
UserStatus если уж на то пошло, но и даже так не нравится
у тебя в классе User будет поле userStatus (или statusUser), что пахнет дерьмом
мб StudyStatus?

2022-06-22 23:22 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/CustomStudentDetailService.java
> +            this.statusUser = student.getStatusUser();
ну тут соответственно тоже

2022-06-22 23:23 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +        PlatformUser account = new PlatformUser(null, login, password,StatusUser.STUDY, roles, new PersonalData(), new UserSettings());
не хватает пробела, научись ctrl+alt+L, либо включи автоматическое форматирование при коммита в идее

2022-06-22 23:24 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +        saveUser(adminLogin, adminPassword, StatusUser.STUDY, Role.USER, Role.ADMIN);
для админов я думаю резонно статус WORK выставлять, тк админы - бывшие студенты :)

2022-06-22 23:24 UTC, nekromant322 requested changes
чейнджи по неймингу, по сути все нравится

2022-06-23 06:19 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/model/enums/StatusUser.java
> +public enum StatusUser{
А разве BAN  подходит под study status? Ну тип это же не статус обучения

2022-06-23 06:22 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/util/InitializationService.java
> +        saveUser(adminLogin, adminPassword, StatusUser.STUDY, Role.USER, Role.ADMIN);
Исправил)

2022-06-23 06:26 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/model/enums/StatusUser.java
> +package com.override.model.enums;
А почему тогда остальные enum не вынесли в эту папку? 

![изображение](https://user-images.githubusercontent.com/53444015/175229966-778d0d2c-5e27-40d8-8583-770beddb4d2d.png)

2022-06-23 06:28 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/service/CustomStudentDetailService.java
> +            this.statusUser = student.getStatusUser();
Исправил

2022-06-23 06:43 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/service/PlatformUserService.java
> +        PlatformUser account = new PlatformUser(null, login, password,StatusUser.STUDY, roles, new PersonalData(), new UserSettings());
Исправил

2022-06-23 22:08 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/model/enums/StatusUser.java
> +public enum StatusUser{
ну, как тебе сказать, тогда можно назвать BAD_END или чтото типо того, ну думаю это излешне  
твой нейминг как минимум вырвиглазный

2022-06-23 22:08 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/model/enums/StatusUser.java
> +package com.override.model.enums;
хмм, окей, убедил, оставь где было

2022-06-23 22:10 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/AdminRestController.java
> +    }
а почему бы это не вынести в UserController? ну или что-то типо того  
под @Patch вполне подходит  
а доступ к ендпоинту только админам разрешить  
это отдельный контроллер мне ваще не нравится, выпилить охота

2022-06-23 22:11 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/AdminRestController.java
> +    }
на остальные методы завел задачку, а свой перекинь сам в UserController

2022-06-24 00:15 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/controller/rest/AdminRestController.java
> +    }
сделал

2022-06-24 15:20 UTC, nekromant322 approved these changes

2022-06-24 15:37 UTC, merged