user's reviews page
nekromant322/platform pull request #92
Opened 2022-06-27 02:07 UTC by SofiaK01

![Screenshot 2022-06-27 at 04 34 11](https://user-images.githubusercontent.com/53154670/175844284-2dbe9a4c-2613-4aeb-98c9-33da8266b3ae.jpg)
![Screenshot 2022-06-27 at 05 07 08](https://user-images.githubusercontent.com/53154670/175846839-2a1dd7fe-2d8e-4372-ac88-7db397e7ad3f.jpg)

все ревью и будущие ревью в обратном хронологическом порядке

2022-06-27 02:35 UTC, SofiaK01 commented
решила убрать колонку с логином
![Screenshot 2022-06-27 at 05 34 02](https://user-images.githubusercontent.com/53154670/175849388-44999fcb-db2b-4345-a577-c5e2bb3aa44e.jpg)

2022-06-27 09:15 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/repository/ReviewRepository.java
> +    List<Review> findReviewByStudentLoginAndBookedDate(String student_login, LocalDate bookedDate);
Стоит использовать camel case в названии стринга

2022-06-27 09:31 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +    @GetMapping("/usersReviews")
тут скорее /userReviews, и ниже тоже. Запрос ведь делает один юзер (текущий) и получает только свои ревью, а не всех.

2022-06-27 10:24 UTC, nekromant322 commented on platform_orchestrator/src/main/resources/static/js/usersReviews.js
> +}
стоит запихнуть в utils.js  (если там еще такой функции нет)  
и в целом по коду если где-то еще такое написано, то использовать функцию из ютилсов

2022-06-27 10:25 UTC, nekromant322 requested changes
фиксы по неймингу + правка js

2022-06-28 21:54 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +    @GetMapping("/userReviews")
myReview?

2022-06-28 21:55 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +        return "userReviews";
аналогично

2022-06-28 21:55 UTC, nekromant322 approved these changes, later dismissed
думаю myReview или myReviews будет понятнее, а так в целом все гуд

2022-06-28 21:56 UTC, nekromant322 commented on platform_orchestrator/src/main/resources/static/js/utils.js
> +    return login;
а почему только логин? вдруг где-то нужна будет другая инфа о юзере? можно же будет переиспользовать если целиком вернуть

2022-06-30 00:42 UTC, nekromant322 approved these changes

2022-06-30 00:44 UTC, merged