Refactor user status, add graduate role, add navabar for graduate, ad…
nekromant322/platform pull request #93
Opened 2022-06-27 20:03 UTC by Alekshas

Изменил статусы у юзеров, добавил graduate роль, сделал navabar, добавил тестовых graduate юзеров, добали изменение юзера на graduate при выпуске.

2022-06-27 20:11 UTC, nekromant322 requested changes
выпилить лишний функционал который не относится к задаче и поправить нейминг

2022-06-27 20:11 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +
это тут зачем?

2022-06-27 20:11 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/AdminRestController.java
> +    public ResponseEntity<String> updateUserRole(@PathVariable Long id, @PathVariable Role Role) {
camelCase

2022-06-28 07:52 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +
Так в навбар для выпускников должна быть оплата, вот я ее и прикрутил сюда

2022-06-28 11:20 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +
это же другая задача совсем

2022-06-28 11:20 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +
этот пул реквест решает задачу добавления новой роли

2022-06-28 18:13 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/controller/rest/AdminRestController.java
> +    public ResponseEntity<String> updateUserRole(@PathVariable Long id, @PathVariable Role Role) {
Исправил

2022-06-28 18:20 UTC, Alekshas commented on platform_orchestrator/src/main/java/com/override/controller/PageController.java
> +
Понял, убрал

2022-06-28 18:21 UTC, nekromant322 approved these changes

2022-06-28 18:22 UTC, merged