Added Telegram notifications
nekromant322/platform pull request #96
Opened 2022-06-28 17:02 UTC by seenister

added Telegram notifications when acceptation and cancellation review are happen by mentor

2022-06-28 21:58 UTC, nekromant322 requested changes
убрать дублирование, добавить только нотификации

2022-06-28 21:58 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        notificatorFeign.sendMessage(reviewRepository.findById(id).get().getStudent().getLogin(), "Ментор вынужден был отменить ревью. Попробуйте записаться на другое время", Communication.TELEGRAM);
такие магические константы можно вынести в константы обыкновенные, было б очень недурно

2022-06-28 22:00 UTC, nekromant322 commented
не забыть в тестах добавить проверку на отправку уведомлений

2022-07-04 18:08 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/controller/rest/ReviewRestController.java
> +        }
почему бы не сделать это в сервисе? зачем аж отдельный метод заводить? просто внутри saverOrUpdate либо слать либо не слать  в зависимости getBookedTime()

2022-07-04 18:10 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/service/ReviewServiceTest.java
> +    void saveOrUpdateReviewTelegramNotification() {
public

2022-07-04 18:10 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/service/ReviewServiceTest.java
>      void deleteReview() {
тож public

2022-07-04 18:10 UTC, nekromant322 commented on platform_orchestrator/src/test/java/com/override/service/ReviewServiceTest.java
> +    void deleteReviewTelegramNotification() {
public

2022-07-04 19:07 UTC, Alexander-Sharipov commented on README.md
> +Валидный чат с собой, в который бот сможет прислать сообщение, можно сделать, если собственноручно зарегистрироваться в платформе)
Вообще наверно стоит описать, как это делается:
Помимо Эврики и Оркестратора запускаем микросервисы Уведомлений и Бота (в одно время бота можно запустить только на одной машине), далее находим бота в тг (@MentoringPlatformBot) -> /register (должно прийти сообщение от бота об успешном запросе) -> заходим в роли админа на платформу и одобряем регистрацию -> в чат с ботом приходит логин и пароль -> вводим их -> поздравляю, вы пользователь платформы! :)
P.S.: Если нужно сделать себя или кого-то админом, то это можно сделать в роли админа на вкладке со всеми пользователями ("Повысить" вроде).

2022-07-04 19:18 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +    public static String DELETED_REVIEW_MESSAGE_TELEGRAM = "Ментор вынужден был отменить ревью. Попробуйте записаться на другое время";
ещё может быть случай изменения времени ревью и/или переназвачение ментора на другого

2022-07-04 19:36 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +    public void saveOrUpdateReviewTelegramNotification(ReviewDTO reviewDTO, String username) {
Смотри, есть метод выше, который уже сохраняет или вносит изменения в ревью
Тебе надо сделать метод (отдельно), который будет отправлять уведомления и только
А вызывать этот метод уже из saveOrUpdateReview (кстати Review можно из названия убрать)
Суть в чём: 1-й if - когда ревью только создается, подразумевается, что это делает студент запрос, значит у ревью нет айди и в дто не передается его логин, поэтому сетим логин студента и сохраняем (тут можно ещё отправить уведомление (всем менторам?), что появился новый запрос на ревью)
2-й - когда ментор принимает ревью, тут можно сделать reviewDTO.getMentorLogin() == null и reviewDTO.getBookedTime() != null, сетим логин ментора и сохраняем, а затем отправляем уведомление студенту, что такой-то ментор назначил/подтвердил ревью на такое-то время
3-й - когда ревью отменяется, тут всё просто: в методе удаления ревью вызываем метод отправки уведомления с соответствующим текстом
4-й - когда в уже подтвержденное ревью вносятся изменения:  reviewDTO.getMentorLogin() != null и reviewDTO.getBookedTime() != null, то можно сравнить логин текущего пользователя с логином ментора из ДТО и если они различаются, то отправить уведомление об изменении ментора с указанием времени (оно может отличаться, а может и нет, это не важно, ведь изменение всё равно есть и лучше время указать), а если логины одинаковые, то отправить уведомление об изменении времени

2022-07-04 19:38 UTC, Alexander-Sharipov commented on platform_orchestrator/src/test/java/com/override/service/ReviewServiceTest.java
> +    void saveOrUpdateReviewTelegramNotification() {
я думал в методах теста лучше наоборот уменьшить видимость, но если так, то public надо проставить и выше (в моих методах) :)

2022-07-05 20:18 UTC, seenister commented on platform_orchestrator/src/test/java/com/override/service/ReviewServiceTest.java
>      void deleteReview() {
поняла, а в итоге остальные методы в этом классе тоже стоит сделать public ?

2022-07-05 21:10 UTC, seenister commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +    public static String DELETED_REVIEW_MESSAGE_TELEGRAM = "Ментор вынужден был отменить ревью. Попробуйте записаться на другое время";
это да, но у меня была задачка только на отмену и подтверждение. Но, если нужно, могу добавить.

2022-07-05 21:24 UTC, seenister commented on README.md
> +Валидный чат с собой, в который бот сможет прислать сообщение, можно сделать, если собственноручно зарегистрироваться в платформе)
Да, хорошо. Я добавлю тогда.

2022-07-06 08:02 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +    public static String DELETED_REVIEW_MESSAGE_TELEGRAM = "Ментор вынужден был отменить ревью. Попробуйте записаться на другое время";
![image](https://user-images.githubusercontent.com/94536519/177500894-d37ebad3-ec13-468e-b317-6802ccf17363.png)
:)

2022-07-06 15:49 UTC, seenister commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +    public static String DELETED_REVIEW_MESSAGE_TELEGRAM = "Ментор вынужден был отменить ревью. Попробуйте записаться на другое время";
о, странно. Я не видела, сейчас тогда добавлю.

2022-07-08 20:06 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +                    new Authority(2L, "ROLE_ADMIN"));
Если сменит кто-нибудь порядок создание енама, это сломается

2022-07-08 20:13 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +            System.out.println("Такой логин: " + login + " Telegram не существует");
Ошибка не говорит о том, что нет такого логина

2022-07-08 20:13 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        if (reviewDTO.getBookedTime() != null && reviewDTO.getMentorLogin() == "") {
Вот эти if в if'е это вообще пиздец, уверен, что можно придумать и лучше

2022-07-08 20:13 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +                sendMessage(mentor.getLogin(), NEW_REVIEW_MESSAGE_TELEGRAM +
Просто для красоты и удобства, я бы использовал String.format() и строки соответственно изменить

2022-07-08 20:13 UTC, kemenchik commented on platform_orchestrator/src/main/java/com/override/repository/PlatformUserRepository.java
> +    List<PlatformUser> findByAuthoritiesContains(Authority authority);
Можно сделать метод аля List<PlatformUser> findByAuthoritiesNameContains(String authorityName)

2022-07-09 06:54 UTC, Alexander-Sharipov commented on README.md
>  Для инициализации тестовых данных необходимо перейти на ендпоинт `/init`
![image](https://user-images.githubusercontent.com/94536519/178095248-bafc2b4d-06d4-4125-aa24-a0b3a185777a.png)
а почему удалила этот кусок то?

2022-07-09 07:26 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        if (reviewDTO.getBookedTime() != null && reviewDTO.getMentorLogin() == "") {
уверена, что reviewDTO.getMentorLogin() == "", а не null?
По идее пустой строкой нигде не заполняется это поле, насколько я помню.

2022-07-09 07:32 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +                        userLogin + " в " + reviewDTO.getBookedTime() + reviewDTO.getBookedDate(), Communication.TELEGRAM);
между временем и датой надо пробел наверно добавить

2022-07-09 07:41 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        if (reviewDTO.getId() == null && reviewDTO.getStudentLogin() == null) {
вот этот иф надо самым первым сделать, так логичнее мне кажется

2022-07-09 07:54 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
>       */
возможно стоит скорректировать javadoc, чтобы было понятнее, зачем столько if-ов в методе

2022-07-09 07:54 UTC, Alexander-Sharipov requested changes
В целом, норм. Внести немного изменений и можно мержить. Ну, и конфликты порешать)

2022-07-10 14:34 UTC, seenister commented on README.md
>  Для инициализации тестовых данных необходимо перейти на ендпоинт `/init`
Так, а я не знаю почему удалилось. Скорее всего это я намудрила, когда конфликт решала

2022-07-10 14:34 UTC, seenister commented on README.md
>  Для инициализации тестовых данных необходимо перейти на ендпоинт `/init`
Сейчас исправлю

2022-07-10 16:16 UTC, seenister commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        if (reviewDTO.getBookedTime() != null && reviewDTO.getMentorLogin() == "") {
Там была проблема с фронтенда. Приходит пустая строка вместо null.

2022-07-10 16:19 UTC, seenister commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        if (reviewDTO.getBookedTime() != null && reviewDTO.getMentorLogin() == "") {
Я выше по коммиту советовалась с Саней и он сказал, что лучше сделать так, ибо он делал эту фичу раньше.
![image](https://user-images.githubusercontent.com/60066678/178153078-a6e79650-5394-4e0c-8322-6b5e5c2bdc80.png)

2022-07-10 17:24 UTC, seenister commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +                    new Authority(2L, "ROLE_ADMIN"));
Сейчас создали в проекте отдельную задачку по этой проблеме

2022-07-10 17:25 UTC, seenister commented on platform_orchestrator/src/main/java/com/override/repository/PlatformUserRepository.java
> +    List<PlatformUser> findByAuthoritiesContains(Authority authority);
Ответила чуть выше

2022-07-11 17:59 UTC, Alexander-Sharipov commented on README.md
> +сообщение, можно сделать, если собственноручно зарегистрироваться в платформе)
Убери скобки и в конце добавь двоеточие
Типа инструкция же ниже

2022-07-11 18:00 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/repository/PlatformUserRepository.java
> +    List<PlatformUser> findByAuthoritiesContains(Authority authority);
а искать по имени Authority не получилось? так надежнее мне кажется

2022-07-11 18:02 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +     * if the logins are the same, a time change notification is sent.
лучше перепиши на русском языке (да, я знаю, что сам написал на англ :) ), и не надо прописывать условия в if, просто опиши в каких случаях будет производиться то или иное действие. (Например, моя строка про студента)
И мою часть тоже переведи плиз)

2022-07-11 18:03 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +                    new Authority(2L, "ROLE_ADMIN"));
создавать новую Authority для поиска админов такая себе идея, лучше попробуй все таки по имени Authority искать)

2022-07-11 18:07 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        }
else if ->

2022-07-11 18:17 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +            System.out.println("FeignException. Возможно, проблема в том, что логин " + login + " Telegram не существует");
Не стоит так писать)
Представь, что ты получила такое исключение и сообщение к ней такое. Если не знаешь, что написать, то посмотри на задачу метода и опиши обратное. В данном случае метод должен отправить сообщение, значит при исключении можно вывести, что "Не удалось отправить сообщение" или что-то типа того. Можно ещё параметров добавить, мол откуда куда зачем и тд.

2022-07-11 18:19 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +            System.out.println("FeignException. Возможно, проблема в том, что логин " + login + " Telegram не существует");
Ещё неплохо бы писать исключение в лог, а не глотать его)

2022-07-12 13:59 UTC, seenister commented on platform_orchestrator/src/main/java/com/override/repository/PlatformUserRepository.java
> +    List<PlatformUser> findByAuthoritiesContains(Authority authority);
Толя сделал эту задачу отдельной https://trello.com/c/2o5FAVwT/136-%D1%80%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3-%D0%BE%D0%BA%D0%BE%D0%BB%D0%BE-platformuserrepository

2022-07-12 14:01 UTC, seenister commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +     * if the logins are the same, a time change notification is sent.
окей

2022-07-12 14:01 UTC, seenister commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +                    new Authority(2L, "ROLE_ADMIN"));
ответила выше

2022-07-12 14:40 UTC, seenister commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        }
Что ты имел ввиду?

2022-07-12 16:19 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        }
добавить сюда else надо между предыдущим if и следующим

2022-07-12 16:20 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/repository/PlatformUserRepository.java
> +    List<PlatformUser> findByAuthoritiesContains(Authority authority);
ок

2022-07-12 16:29 UTC, seenister commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +        }
а есть ли в этом смысл? У нас же все равно не может быть вхождения в два эти if одновременно

2022-07-13 14:10 UTC, nekromant322 commented on platform_orchestrator/src/main/java/com/override/service/LessonProgressService.java
> +
зачем?

2022-07-13 14:11 UTC, nekromant322 submitted a review, later dismissed

2022-07-13 14:14 UTC, seenister commented on platform_orchestrator/src/main/java/com/override/service/LessonProgressService.java
> +
всё, убрала)

2022-07-13 14:31 UTC, Alexander-Sharipov commented on README.md
> +который бот сможет прислать сообщение, можно сделать, если собственноручно зарегистрироваться в платформе.
Удали всё, что после ("Повысить"). Дублирование получается, не заметил в прошлый раз.

2022-07-13 14:33 UTC, Alexander-Sharipov commented on platform_orchestrator/src/main/java/com/override/service/ReviewService.java
> +     * Если ревью новое, то логин пользователя присваивается ученику.
"Если ревью новое, то логин пользователя присваивается ученику." - удали, эта строка теперь лишняя получается, ниже написано по сути то же самое, но подробнее.

2022-07-13 14:37 UTC, Alexander-Sharipov approved these changes

2022-07-13 14:39 UTC, merged